### ISSUE TITLE
Improve MySQL Password support

### ISSUE THREAD

**Issue by theory** [theory/sqitch#150]
In #100, we discussed adding support for `~/.my.cnf` in order to improve password handling, perhaps by taking advantage of [MySQL::Config](https://metacpan.org/module/MySQL::Config).

We also might want to consider making use of the [`MYSQL_PWD` environment variable](https://dev.mysql.com/doc/refman/5.6/en/environment-variables.html) for use with `mysql`, rather than the `--password` option. That way it is less likely to appear in the process table. This is just like the current use of the `PGPASSWORD` environment variable by the Postgres engine.

**Comment by ealter** [comment]
The [mysql docs](https://dev.mysql.com/doc/refman/5.6/en/password-security-user.html) say that this method is very insecure. If any user runs `ps e | grep mysql` while sqitch is making a change, they'll be able to see the password in the environmental variable list.

I guess I should probably just open an issue for this, but do you think it'd be possible to do a more secure password authentication?

**Comment by theory** [comment]
Well, Sqitch uses MySQL::Config to read the config files as of a3849dc. As far as I could tell, that was the recommended way to get passwords for MySQL. But I agree the security of it is far from ideal. I'd welcome a PR with improved MySQL password support (along with an appropriate update to [sqitch-passwords](https://github.com/theory/sqitch/blob/master/lib/sqitch-passwords.pod).
