### ISSUE TITLE
Add ability to specify a prefix for registry tables

### ISSUE THREAD

**Issue by ahawkins318** [theory/sqitch#172]
I am trying to set up sqitch in an environment where I don't have full permissions on the database I am managing. Due to these permissions constraints, I am not able to make use of the sqitch_schema config option.

(My specific situation is: we have a single oracle development database instance at my organization, with a schema set up for each developer to use as his/her own sandbox. I have permissions only to my own schema, and can't create new schemas or create tables on any other schema but my own.) 

This means my sqitch metadata and my everything else must all live happily together in the same schema. BUT THEN SADNESS - there is name collision! 

I propose adding a config option, 'sqitch_prefix' that would be prepended to the names of each sqitch metadata table (changes, dependencies, etc). This would avoid name collisions in a flexible way. 

I am currently working on a patch to provide this feature for oracle. Would this be useful to others? I'd appreciate any feedback.

**Comment by drmuey** [comment]
@stefansbv If I am seeing this right this change means that, for engines that support it:

Adding with_registry_prefix = 1 to sqitch.conf

Will make sqitch use tables prefixed w/ sqitch_ inside the database being deployed? instead of seperate database.

If so, AWESOME!!! +1

**Comment by stefansbv** [comment]
Yes @drmuey that is the idea.

**Comment by drmuey** [comment]
thanks! can't wait for this to land :+1:

**Comment by theory** [comment]
@stefansbv You haven't had a chance to add tests yet, have you?

**Comment by stefansbv** [comment]
@theory No, not than, I just changed the `alt_engine_params` to use the feature, and that is how I tested it.

Now I understand that what you wanted was a separate test, maybe something like this?:  b4a207dd0c

**Comment by theory** [comment]
Yeah, plus tests that all the various queries work properly. Probably should add loop to `t/libDBIEngineTest` that does the current database tests, then does them all again with the `with_registry_prefix` feature enabled.

Also, what needs to happen to make sure that all of the engines can use this feature?

**Comment by stefansbv** [comment]
- In the engine SQL scripts add a `:prefix:` string before the table name;
- In the engine modules use variables instead of table names and get the table name into the variable using the `_get_registry_table` function;

The code to replace `:prefix:` with `sqitch_` or to remove it in the SQL scripts, is currently in the `initialize` method, and should be factored out.

The patch is applied on Sqitch v0.997.

**Comment by theory** [comment]
Any chance of a rebase?

**Comment by stefansbv** [comment]
Yes, there is a chance.

**Comment by stefansbv** [comment]
I think is done an OK (https://github.com/stefansbv/sqitch/tree/registry-prefix).

**Comment by theory** [comment]
Okay @stefansbv, would you submit a pull request?

**Comment by stefansbv** [comment]
@theory, yes, but note that the changes for oracle engine are not included.

**Comment by theory** [comment]
No? Why not?

**Comment by stefansbv** [comment]
Can't you take it from @ahawkins318?

**Comment by theory** [comment]
Uh. I thought your work was an extension of his. Are these now two separate patches?

**Comment by stefansbv** [comment]
It is an extension with Firebird and MySQL. I don't know Oracle, and I didn't import that part.

**Comment by theory** [comment]
@ahawkins318 Any chance of a rebase of your code, too?

**Comment by ahawkins318** [comment]
Sure, let me take a look. You want me to rebase on top of https://github.com/stefansbv/sqitch/tree/registry-prefix , right?

**Comment by theory** [comment]
No, I think you should rebase on theory/master, and then @stefansbv can rebase his branch on yours.

**Comment by ahawkins318** [comment]
This is a non-trivial rebase since there has been a new registry table added since I last looked at this. If I don't get it finished today I should have it by Monday, hopefully.

**Comment by theory** [comment]
Oh, thanks. No rush.

**Comment by stefansbv** [comment]
I created a new branch `reg-prefix` in my [fork](https://github.com/stefansbv/sqitch.git) where I merged `ahawkins/registry-prefix` and then my `stefansbv/registry-prefix`, (I have a very basic understanding of rebase), but I hope this works too.

**Comment by theory** [comment]
@stefansbv Is it ready to be put into a pull request, then?

**Comment by stefansbv** [comment]
@theory Was not ready, now it is :)

The config command for Firebird is:

    sqitch config --local --add engine.firebird.with_registry_prefix 1

**Comment by stefansbv** [comment]
With MariaDB 10.0.18 I get 3 errors, but the tests pass:
```
    # Subtest: Test the with_registry_prefix feature
        ok 1 - Create engine with alternate params
        ok 2 - No init, earliest change
        ok 3 - No init, no latest change
        ok 4 - Database should no longer seem initialized
ERROR 1304 (42000) at line 158 in file: '/tmp/xZzdB7BD0f': FUNCTION checkit already exists
ERROR 1359 (HY000) at line 167 in file: '/tmp/xZzdB7BD0f': Trigger already exists
ERROR 1359 (HY000) at line 178 in file: '/tmp/xZzdB7BD0f': Trigger already exists
        ok 5 - Initialize the database again
```

**Comment by theory** [comment]
Closing; see #247 for ongoing work.
