### ISSUE TITLE
Installation on linux

### ISSUE THREAD

**Issue by acrobat** [theory/sqitch#173]
Maybe you should add this method to the install instructions for linux, it's an easy way to install (less issues than the ./Build install) and an ideal workaround before we get an apt package see #163 

```
sudo apt-get update
sudo apt-get install cpanminus perl
cpanm --quiet --notest App::Sqitch
```

**Comment by yletallec** [comment]
On my fresh Ubuntu 14.04.2 LTS VM Install I got the error :

DBD::Pg 2.0 required to manage PostgreSQL

Solved by installing :

apt-get install libdbd-pg-perl

**Comment by theory** [comment]
@yletallec Yeah, that's documented in both the "Debian sid" and "Apt + cpanminus" sections. Is it needed somewhere else?

**Comment by yletallec** [comment]
Oops, I didn’t notice.
Sorry for the inconvenience
Thank you for Sqitch good piece of SW.

**Comment by theory** [comment]
Thanks, reports always appreciated!

**Comment by dredozubov** [comment]
I experience this on OS X 10.11:
```
DBD::Pg 2.0 required to manage PostgreSQL
```

Any suggestions?

**Comment by theory** [comment]
You'll need to install DBD::Pg. How did you install Sqitch?

**Comment by BenMorganIO** [comment]
Hey guys,

I'm currently experiencing this on a new work Mac. Is there something to install on Mac?

**Comment by MaxGabriel** [comment]
Try `brew tap theory/sqitch` and `brew install sqitch_pg`. See here: http://sqitch.org/

I ran into this when I ran `brew install sqitch` instead of `sqitch_pg`

**Comment by theory** [comment]
If you don't install one of the database variants like `sqitch_pg` or `sqitch_sqlite`, you will not be able to use Sqitch with any database engine.
