### ISSUE TITLE
Deploy to database with root password

### ISSUE THREAD

**Issue by trezker** [theory/sqitch#183]
I can not find anywhere documented the possibility to deploy to a database where you need a password.

All the guides assume you're working against a database without password, but what self respecting developer would not have a password on the database superuser?

**Comment by theory** [comment]
Forgot about this issue. Should be resolved by the addition of the [sqitch-passwords](https://github.com/theory/sqitch/blob/master/lib/sqitch-passwords.pod) guide, added in d8b92c3.
