### ISSUE TITLE
Error "DBD::Oracle 1.23 required to manage Oracle"

### ISSUE THREAD

**Issue by teopost** [theory/sqitch#206]
I have installed sqitch on ubuntu 14.10 with oracle 12c.
When executing sqitch deploy db:oracle://scott:tiger@/flipr_test, I have this error

DBD::Oracle 1.23 required to manage Oracle

**Comment by theory** [comment]
So, is DBD::Oracle installed?

**Comment by teopost** [comment]
Hi,
   excuse the delay.
If I run the installation as oracle user
```
cpan App :: Sqitch DBD :: Oracle
```
Installation fails for permission problems.
If I run as root seems to work, but if I run
```
sqitch deploy db:oracle://test:test@/flipr_test
```
I get this error
```
Adding registry tables to db:oracle://test:@/flipr_test
Can't exec "/u01/app/oracle/product/12.1.0.2/dbhome_1/sqlplus": Permesso negato at /usr/local/share/perl/5.18.2/IPC/Run3.pm line 403.

/u01/app/oracle/product/12.1.0.2/dbhome_1/sqlplus unexpectedly returned exit value 72057594037927935
oracle@tangeri:~/flipr$ sqitch deploy db:oracle://test:test@/flipr_test

```

**Comment by theory** [comment]
Sounds like your copy of `sqlplus` isn't properly configured. What happens if you run

    sqlplus test/test@flipr_test

?

**Comment by teopost** [comment]
Oracle instance work fine:

```
oracle@tangeri:~$ sqlplus test/test@flipr_test

SQL*Plus: Release 12.1.0.2.0 Production on Wed Jan 14 17:27:59 2015

Copyright (c) 1982, 2014, Oracle.  All rights reserved.

Last Successful login time: Wed Jan 14 2015 14:55:49 +01:00

Connected to:
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options

SQL> 

```

**Comment by theory** [comment]
Is that also true for

    /u01/app/oracle/product/12.1.0.2/dbhome_1/sqlplus test/test@flipr_test

?

**Comment by teopost** [comment]
Yes, but sqlplus is into /u01/app/oracle/product/12.1.0.2/dbhome_1/bin folder.

```
oracle@tangeri:/u01/app/oracle/product/12.1.0.2/dbhome_1/bin$ /u01/app/oracle/product/12.1.0.2/dbhome_1/bin/sqlplus test/test@flipr_test

SQL*Plus: Release 12.1.0.2.0 Production on Mon Jan 19 09:06:55 2015

Copyright (c) 1982, 2014, Oracle.  All rights reserved.

Last Successful login time: Wed Jan 14 2015 17:27:59 +01:00

Connected to:
Oracle Database 12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production
With the Partitioning, OLAP, Advanced Analytics and Real Application Testing options

SQL> 
```

**Comment by theory** [comment]
Well no wonder it doesn't work. Try telling Sqitch the proper place to fiddle `sqlplus`:

    sqitch config --user engine.oracle.client /u01/app/oracle/product/12.1.0.2/dbhome_1/bin/sqlplus

That will set a the config in `~/.sqitch/sqitch.conf`, so it will work for all of your Oracle Sqitch projects with your account on that system.

**Comment by teopost** [comment]
Thank you. Now it work

**Comment by theory** [comment]
\o/
