### ISSUE TITLE
take advantage of docker for install

### ISSUE THREAD

**Issue by docteurklein** [theory/sqitch#207]
I just released a docker image for sqitch:pgsql.
I wanted to let you know: https://registry.hub.docker.com/u/docteurklein/sqitch/
Now using sqitch is as simple as this one liner:

    docker run --rm docteurklein/sqitch:pgsql

**Comment by theory** [comment]
Oh sweet! I need to try Docker…

**Comment by theory** [comment]
Added it to the home page in 933905a. Thanks!
