### ISSUE TITLE
Regression in 0.998: Unable to create registry schema

### ISSUE THREAD

**Issue by jplindstrom** [theory/sqitch#208]
We just upgraded a machine from 0.997 to 0.998 today and now the deploy doesn't seem to be able to create the registry schema:

(at this point, there is no schema bat_sqitch, it was just dropped)

    $ sqitch deploy
    Unknown database 'bat_sqitch'

This is with a custom registry name, if I change that to the default one, same thing:

    $ sqitch deploy
    Unknown database 'sqitch'

Here's the sqitch.conf:

```
[core]
	engine = mysql
[engine "mysql"]
	client = /usr/bin/mysql
	target = current
	registry = bat_sqitch

[user]
    name = My Name
[deploy]
	verify = true
[rebase]
	verify = true


[target "current"]
	uri = db:mysql://A-USER:A-PASSWORD@localhost/bat
    registry = bat_sqitch
```

**Comment by theory** [comment]
Thanks for the report. I just verified this issue with the v0.998 release, but it's fixed in `master`. I've fixed a few annoyances since release. Would you install from Git and confirm?

**Comment by jplindstrom** [comment]
Yep, that seems to work fine!

**Comment by theory** [comment]
Great, thank you. I will put out v0.999 soon.

**Comment by jplindstrom** [comment]
Any idea of when this will be released? Just installed on a machine and got the broken version again.

**Comment by theory** [comment]
I'll get a release out this week. Sorry for the hassle.
