### ISSUE TITLE
Use semver as release version standard

### ISSUE THREAD

**Issue by acrobat** [theory/sqitch#211]
Now we are getting close to a stable release it's maybe a good time to switch to [semantic versioning](http://semver.org/)

the "rules" are easy en will make the life of the users of this tool easier (on upgrading to versions etc)

X.Y.Z

X: major release - BC breaks possible
Y: minor release - this version bumps will introduce new features without BC break
Z: patch release - bugfix release without features 

Don't know if you like this kind of versioning system but it's just a suggestion ;)

**Comment by theory** [comment]
I do like semver; [PGXN](http://pgxn.org/) requires it and I wrote [SemVer](https://metacpan.org/module/SemVer). But it's not great for Perl modules. I plan to switch to  `1.xx` format with 1.0; it's the simplest version you can have (other than a single integer, I guess).

**Comment by acrobat** [comment]
Ok no problem! But why is semver not great for Perl modules? Just curious :)

**Comment by theory** [comment]
It's just asking for more trouble than it's worth, though I have made it work okay for the SemVer module itself. Anyway, I more or less follow [these recommendations](http://www.dagolden.com/index.php/369/version-numbers-should-be-boring/) by @dagolden, though I admit I haven't read it in a while.
