### ISSUE TITLE
unknown option '--skip-pager'

### ISSUE THREAD

**Issue by gadelat** [theory/sqitch#213]
I have MariaDB installed in windows and I'm connecting to MariaDB server on Debian VM.
```
PS C:\xampp\htdocs\db> sqitch deploy db:mysql://sqitch@/test
Adding registry tables to db:mysql://sqitch@/sqitch
C:\Program: unknown option '--skip-pager'
"C:\Program Files\MariaDB 10.0\bin\mysql.exe" unexpectedly returned exit value 2

C:\xampp\htdocs\db> sqitch --version
sqitch.bat (App::Sqitch) 0.999
```
MariaDB in Windows is 10.0.15.
Server is MariaDB 10.0.16-MariaDB-1~wheezy-log.
Sqitch was installed through ActivePerl 5.16.3.1603

**Comment by theory** [comment]
Oh, so it [looks like](https://mariadb.com/kb/en/mariadb/mysql-command-line-client/) now uses `--disable-pager` instead of `--skip-pager`. Would be nice if they kept parity with [mysql](http://dev.mysql.com/doc/refman/5.6/en/mysql-command-options.html).

Can you tell show a command to demonstrate whether the instance of the `mysql` client supports `--skip-pager` or `--disable-pager`? Or maybe convince the Maria folks to allow `--skip-pager` as an alias?

**Comment by gadelat** [comment]
Windows:
```
C:\Program Files\MariaDB 10.0\bin> mysql --help|grep pager
C:\Program Files\MariaDB 10.0\bin>
```
Debian:
```
gadelat@debian:/var/www$ mysql --help|grep pager
  --pager[=name]      Pager to use to display results. If you don't supply an
                      option, the default pager is taken from your ENV variable
                      PAGER. Valid pagers are less, more, cat [> filename],
                      work in batch mode. Disable with --disable-pager. This
```
It seems pager function is specific for unix, so it's missing from Windows client.

**Comment by theory** [comment]
Oh. Is that true of the MySQL `mysql` client, too?

**Comment by theory** [comment]
Here are the options passed to `mysql`:

        push @ret => (
            '--skip-pager',
            '--silent',
            '--skip-column-names',
            '--skip-line-numbers',
        );

Which are invalid on Windows, and which are only invalid with the Maria `mysql` client?

**Comment by gadelat** [comment]
skip-pager is missing from both MariaDB and official MySQL windows clients. Rest of options are available in both clients.

**Comment by theory** [comment]
Is there a command to the Maria `mysql` client to identify it as Maria and not MySQL? `--version` or something?

**Comment by gadelat** [comment]
Yeah
```
C:\Program Files\MariaDB 10.0\bin> mysql --version
mysql  Ver 15.1 Distrib 10.0.15-MariaDB, for Win64 (x86)
```
But what for? You don't need to differentiate them to solve this bug since --no-pager is missing from both of them.

**Comment by theory** [comment]
The MySQL version supports `--skip-pager`, while Maria wants `--disable-pager`.

**Comment by gadelat** [comment]
Tried it now, Maria works with both

**Comment by theory** [comment]
Let me know if that fixes the issue for you, @gadelat.

**Comment by theory** [comment]
Oh, Maria on LInix is okay with `--skip-pager`?

**Comment by gadelat** [comment]
Yes.
Linux MariaDB client works with both.
Windows MariaDB client works with neither.
Windows MySQL client works with neither.

This patch does not fix this issue. *-pager option needs to be removed for Win platform.

**Comment by theory** [comment]
Got it.

**Comment by theory** [comment]
Let me know if that *actually* fixes the issue for you, @gadelat. Thanks!
