### ISSUE TITLE
Sqitch plan --abrev

### ISSUE THREAD

**Issue by aklaver** [theory/sqitch#220]
sqitch plan --help
 
Formatting
        --abrev                       abbreviate change IDs

sqitch help plan

"--abbrev"

--abbrev seems to be the right one.  
The reason I am finding these things is that I am actively kicking the tires on Sqitch. I like it and plan on using it going forward for my database schema changes. In fact I going to do a demo at the Whatcom PUG tonight to spread the word. Thanks for the program.

**Comment by theory** [comment]
Awesome, thanks!
