### ISSUE TITLE
On error, status command doesn't exit with an error code

### ISSUE THREAD

**Issue by tsibley** [theory/sqitch#229]
I found myself in a situation where `sqitch status` reports:

```
Cannot find this change in schema/sqitch.plan
Make sure you are connected to the proper database for this project.
```

But the exit status of the command is still 0.  I'd expect the exit status to be non-zero in an error case like this.  (I know what the cause of the "change not in plan" error is and can address it, this is just about the exit status.)

**Comment by theory** [comment]
Well, it's showing the status of the database, which you can do when there is no plan file. Maybe it should exit with 2 if there is a plan that appears to be for the relevant project and the change can't be found, and 1 if there is no plan file for it?

**Comment by theory** [comment]
@tsibley Would my suggestion work for you?

**Comment by tsibley** [comment]
Sorry for dropping this.  As I understand your suggestion, status would return 2 in the situation I reported, which works for me!

Basically, my expectation is that any kind of error or exceptional state returns a non-zero exit status.

**Comment by theory** [comment]
Uh, it appears to be an error already:

     > sqitch status
    # On database local
    # Project:  configuration
    # Change:   e86a2df5e7f296b89897321cf02365edde5241bd
    # Name:     blah
    # Deployed: 2015-08-11 11:35:00 -0700
    # By:       David E. Wheeler <david@justatheory.com>
    # 
    Cannot find this change in sqitch.plan
    Make sure you are connected to the proper database for this project.
    > echo $?
    2

Am I missing something, @tsibley?

**Comment by tsibley** [comment]
Hmm, maybe this changed at some point?

The version I believe I saw this on was `sqitch (App::Sqitch) 0.997`.

**Comment by theory** [comment]
Hrm. Not that I can see in the changes. Oh well, as long as it's fixed!
