### ISSUE TITLE
LOCALE test failure when installing from cpanm

### ISSUE THREAD

**Issue by shantanubhadoria** [theory/sqitch#230]
Attaching my build LOG:

    cpanm (App::cpanminus) 1.7001 on perl 5.018002 built for i686-linux-gnu-thread-multi-64int
    Work directory is /root/.cpanm/work/1430288101.16106
    You have make /usr/bin/make
    You have LWP 6.05
    You have /bin/tar: tar (GNU tar) 1.27.1
    Copyright (C) 2013 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    
    Written by John Gilmore and Jay Fenlason.
    --> Working on DWHEELER/App-Sqitch-0.9991.tar.gz
    Fetching http://www.cpan.org/authors/id/D/DW/DWHEELER/App-Sqitch-0.9991.tar.gz
    -> OK
    Unpacking App-Sqitch-0.9991.tar.gz
    Entering App-Sqitch-0.9991
    Checking configure dependencies from META.json
    Checking if you have Module::Build 0.35 ... Yes (0.4003)
    Checking if you have Module::Build 0.36 ... Yes (0.4003)
    Configuring App-Sqitch-0.9991
    Running Build.PL
    Checking prerequisites...
      recommends:
        *  Type::Tiny::XS is not installed
    
    ERRORS/WARNINGS FOUND IN PREREQUISITES.  You may wish to install the versions
    of the modules indicated above before proceeding with this installation
    
    Created MYMETA.yml and MYMETA.json
    Creating new 'Build' script for 'App-Sqitch' version '0.9991'
    -> OK
    Checking dependencies from MYMETA.json ...
    Checking if you have User::pwent 0 ... Yes (1.00)
    Checking if you have Test::Exception 0 ... Yes (0.32)
    Checking if you have warnings 0 ... Yes (1.18)
    Checking if you have Moo::Role 0 ... Yes (1.004002)
    Checking if you have overload 0 ... Yes (1.22)
    Checking if you have IPC::System::Simple 1.17 ... Yes (1.25)
    Checking if you have Carp 0 ... Yes (1.29)
    Checking if you have Scalar::Util 0 ... Yes (1.27)
    Checking if you have Locale::TextDomain 1.20 ... Yes (1.24)
    Checking if you have URI::db 0.15 ... Yes (0.15)
    Checking if you have IPC::Run3 0 ... Yes (0.048)
    Checking if you have parent 0 ... Yes (0.225)
    Checking if you have File::Temp 0 ... Yes (0.23)
    Checking if you have Type::Utils 0 ... Yes (1.000005)
    Checking if you have Encode::Locale 0 ... Yes (1.03)
    Checking if you have Encode 0 ... Yes (2.49)
    Checking if you have List::Util 0 ... Yes (1.27)
    Checking if you have Moo::sification 0 ... Yes (undef)
    Checking if you have lib 0 ... Yes (0.63)
    Checking if you have if 0 ... Yes (0.0602)
    Checking if you have Clone 0 ... Yes (0.36)
    Checking if you have FindBin 0 ... Yes (1.51)
    Checking if you have Digest::SHA 0 ... Yes (5.84_01)
    Checking if you have namespace::autoclean 0.16 ... Yes (0.24)
    Checking if you have Throwable 0.200009 ... Yes (0.200009)
    Checking if you have Getopt::Long 0 ... Yes (2.39)
    Checking if you have Sub::Exporter::Util 0 ... Yes (0.986)
    Checking if you have Test::Deep 0 ... Yes (0.112)
    Checking if you have List::MoreUtils 0 ... Yes (0.33)
    Checking if you have File::Basename 0 ... Yes (2.84)
    Checking if you have String::ShellQuote 0 ... Yes (1.03)
    Checking if you have Template::Tiny 0.11 ... Yes (1.12)
    Checking if you have IO::Pager 0 ... Yes (0.34)
    Checking if you have Test::File::Contents 0.20 ... Yes (0.21)
    Checking if you have String::Formatter 0 ... Yes (0.102084)
    Checking if you have Test::More 0.94 ... Yes (1.001014)
    Checking if you have strict 0 ... Yes (1.07)
    Checking if you have utf8 0 ... Yes (1.10)
    Checking if you have Test::Dir 0 ... Yes (1.014)
    Checking if you have PerlIO::utf8_strict 0 ... Yes (0.005)
    Checking if you have Type::Library 0.040 ... Yes (1.000005)
    Checking if you have File::Spec::Functions 0 ... Yes (3.40)
    Checking if you have Moo 1.002000 ... Yes (1.004002)
    Checking if you have Test::File 0 ... Yes (1.41)
    Checking if you have Pod::Usage 0 ... Yes (1.61)
    Checking if you have Hash::Merge 0 ... Yes (0.200)
    Checking if you have Capture::Tiny 0.12 ... Yes (0.24)
    Checking if you have Path::Class 0.33 ... Yes (0.33)
    Checking if you have Sys::Hostname 0 ... Yes (1.17)
    Checking if you have Types::Standard 0 ... Yes (1.000005)
    Checking if you have Test::MockModule 0.05 ... Yes (0.09)
    Checking if you have File::Copy 0 ... Yes (2.26)
    Checking if you have constant 0 ... Yes (1.27)
    Checking if you have Time::HiRes 0 ... Yes (1.9725)
    Checking if you have File::HomeDir 0 ... Yes (1.00)
    Checking if you have Locale::Messages 0 ... Yes (1.24)
    Checking if you have POSIX 0 ... Yes (1.32)
    Checking if you have DBI 0 ... Yes (1.630)
    Checking if you have Term::ANSIColor 2.02 ... Yes (4.02)
    Checking if you have File::Path 0 ... Yes (2.09)
    Checking if you have Try::Tiny 0 ... Yes (0.19)
    Checking if you have Test::NoWarnings 0.083 ... Yes (1.04)
    Checking if you have Devel::StackTrace 1.30 ... Yes (1.30)
    Checking if you have StackTrace::Auto 0 ... Yes (0.200009)
    Checking if you have File::Spec 0 ... Yes (3.40)
    Checking if you have Sub::Exporter 0 ... Yes (0.986)
    Checking if you have DateTime 0 ... Yes (1.06)
    Checking if you have Pod::Find 0 ... Yes (1.60)
    Checking if you have URI 0 ... Yes (1.60)
    Checking if you have Config::GitLike 1.11 ... Yes (1.16)
    Checking if you have Module::Build 0.35 ... Yes (0.4003)
    Checking if you have Time::Local 0 ... Yes (1.2300)
    Building and testing App-Sqitch-0.9991
    Building App-Sqitch
    t/add.t ............. ok
    t/base.t ............ ok
    t/blank.t ........... ok
    t/bundle.t .......... ok
    t/change.t .......... ok
    t/changelist.t ...... ok
    t/checkout.t ........ ok
    t/command.t ......... ok
    t/config.t .......... ok
    t/configuration.t ... ok
    Invalid locale name or id: C.UTF_8
    
    #   Failed test 'no warnings'
    #   at /usr/local/share/perl/5.18.2/Test/NoWarnings.pm line 45.
    # There were 1 warning(s)
    # 	Previous test 3 'as_string_formats should be correct'
    # 	Use of uninitialized value $language in lc at /usr/share/perl5/DateTime/Locale.pm line 246.
    #  at /usr/share/perl5/DateTime/Locale.pm line 246.
    # 	DateTime::Locale::_guess_id('DateTime::Locale', 'C.UTF_8') called at /usr/share/perl5/DateTime/Locale.pm line 209
    # 	DateTime::Locale::load(undef, 'C.UTF-8') called at /usr/lib/perl5/DateTime.pm line 291
    # 	DateTime::_set_locale('App::Sqitch::DateTime=HASH(0x9bf514c)', 'C.UTF-8') called at /usr/lib/perl5/DateTime.pm line 230
    # 	DateTime::_new('App::Sqitch::DateTime', 'year', 2015, 'second', 13, 'day', 29, 'time_zone', 'DateTime::TimeZone::Asia::Singapore=HASH(0x9bd89cc)', ...) called at /usr/lib/perl5/DateTime.pm line 206
    # 	DateTime::new(undef, 'year', 2015, 'time_zone', 'DateTime::TimeZone::Asia::Singapore=HASH(0x9bd89cc)', 'day', 29, 'minute', 15, ...) called at /usr/lib/perl5/DateTime.pm line 317
    # 	DateTime::_new_from_self('App::Sqitch::DateTime=HASH(0x9c00d28)', 'locale', 'C.UTF-8') called at /usr/lib/perl5/DateTime.pm line 1923
    # 	DateTime::set(undef, 'locale', 'C.UTF-8') called at t/datetime.t line 55
    # 
    # Looks like you planned 33 tests but ran 4.
    # Looks like you failed 1 test of 4 run.
    # Looks like your test exited with 255 just after 4.
    t/datetime.t ........ 
    Dubious, test returned 255 (wstat 65280, 0xff00)
    Failed 30/33 subtests 
    t/depend.t .......... ok
    t/deploy.t .......... ok
    t/engine.t .......... ok
    t/engine_cmd.t ...... ok
    t/firebird.t ........ ok
    t/help.t ............ ok
    t/init.t ............ ok
    Invalid locale name or id: C.UTF_8
    
    #   Failed test 'no warnings'
    #   at /usr/local/share/perl/5.18.2/Test/NoWarnings.pm line 45.
    # There were 1 warning(s)
    # 	Previous test 5 'Default date format should be "iso"'
    # 	Use of uninitialized value $language in lc at /usr/share/perl5/DateTime/Locale.pm line 246.
    #  at /usr/share/perl5/DateTime/Locale.pm line 246.
    # 	DateTime::Locale::_guess_id('DateTime::Locale', 'C.UTF_8') called at /usr/share/perl5/DateTime/Locale.pm line 209
    # 	DateTime::Locale::load(undef, 'C.UTF-8') called at /usr/lib/perl5/DateTime.pm line 291
    # 	DateTime::_set_locale('App::Sqitch::DateTime=HASH(0x9f1e1fc)', 'C.UTF-8') called at /usr/lib/perl5/DateTime.pm line 230
    # 	DateTime::_new('App::Sqitch::DateTime', 'minute', 15, 'month', 4, 'year', 2015, 'day', 29, ...) called at /usr/lib/perl5/DateTime.pm line 206
    # 	DateTime::new(undef, 'hour', 14, 'nanosecond', 0, 'second', 17, 'locale', 'DateTime::Locale::en_US=HASH(0x9dbd954)', ...) called at /usr/lib/perl5/DateTime.pm line 317
    # 	DateTime::_new_from_self('App::Sqitch::DateTime=HASH(0x9e7bc5c)', 'locale', 'C.UTF-8') called at /usr/lib/perl5/DateTime.pm line 1923
    # 	DateTime::set(undef, 'locale', 'C.UTF-8') called at t/item_formatter.t line 71
    # 
    # Looks like you planned 158 tests but ran 6.
    # Looks like you failed 1 test of 6 run.
    # Looks like your test exited with 255 just after 6.
    t/item_formatter.t .. 
    Dubious, test returned 255 (wstat 65280, 0xff00)
    Failed 153/158 subtests 
    t/linelist.t ........ ok
    Invalid locale name or id: C.UTF_8
    
    #   Failed test 'no warnings'
    #   at /usr/local/share/perl/5.18.2/Test/NoWarnings.pm line 45.
    # There were 1 warning(s)
    # 	Previous test 44 'Instantiate with format "full" and date format "long"'
    # 	Use of uninitialized value $language in lc at /usr/share/perl5/DateTime/Locale.pm line 246.
    #  at /usr/share/perl5/DateTime/Locale.pm line 246.
    # 	DateTime::Locale::_guess_id('DateTime::Locale', 'C.UTF_8') called at /usr/share/perl5/DateTime/Locale.pm line 209
    # 	DateTime::Locale::load(undef, 'C.UTF-8') called at /usr/lib/perl5/DateTime.pm line 291
    # 	DateTime::_set_locale('App::Sqitch::DateTime=HASH(0x97000cc)', 'C.UTF-8') called at /usr/lib/perl5/DateTime.pm line 230
    # 	DateTime::_new('App::Sqitch::DateTime', 'locale', 'C.UTF-8', 'time_zone', 'DateTime::TimeZone::Asia::Singapore=HASH(0x9677204)', 'year', 2015, 'second', 18, ...) called at /usr/lib/perl5/DateTime.pm line 206
    # 	DateTime::new(undef, 'minute', 15, 'nanosecond', 0, 'day', 29, 'month', 4, ...) called at /usr/lib/perl5/DateTime.pm line 317
    # 	DateTime::_new_from_self('App::Sqitch::DateTime=HASH(0x97000e0)', 'locale', 'C.UTF-8') called at /usr/lib/perl5/DateTime.pm line 1923
    # 	DateTime::set(undef, 'locale', 'C.UTF-8') called at /root/.cpanm/work/1430288101.16106/App-Sqitch-0.9991/blib/lib/App/Sqitch/DateTime.pm line 63
    # 	App::Sqitch::DateTime::as_string('App::Sqitch::DateTime=HASH(0x963e2d0)', 'format', 'long') called at t/log.t line 296
    # 
    # Looks like you planned 248 tests but ran 45.
    # Looks like you failed 1 test of 45 run.
    # Looks like your test exited with 255 just after 45.
    t/log.t ............. 
    Dubious, test returned 255 (wstat 65280, 0xff00)
    Failed 204/248 subtests 
    t/mysql.t ........... ok
    t/options.t ......... ok
    t/oracle.t .......... ok
    t/pg.t .............. ok
    t/plan.t ............ ok
    Invalid locale name or id: C.UTF_8
    
    #   Failed test 'no warnings'
    #   at /usr/local/share/perl/5.18.2/Test/NoWarnings.pm line 45.
    # There were 1 warning(s)
    # 	Previous test 41 'Instantiate with format "full" and date format "long"'
    # 	Use of uninitialized value $language in lc at /usr/share/perl5/DateTime/Locale.pm line 246.
    #  at /usr/share/perl5/DateTime/Locale.pm line 246.
    # 	DateTime::Locale::_guess_id('DateTime::Locale', 'C.UTF_8') called at /usr/share/perl5/DateTime/Locale.pm line 209
    # 	DateTime::Locale::load(undef, 'C.UTF-8') called at /usr/lib/perl5/DateTime.pm line 291
    # 	DateTime::_set_locale('App::Sqitch::DateTime=HASH(0xa49f2ec)', 'C.UTF-8') called at /usr/lib/perl5/DateTime.pm line 230
    # 	DateTime::_new('App::Sqitch::DateTime', 'time_zone', 'DateTime::TimeZone::Asia::Singapore=HASH(0xa41b7b4)', 'day', 28, 'minute', 15, 'nanosecond', 0, ...) called at /usr/lib/perl5/DateTime.pm line 206
    # 	DateTime::new(undef, 'month', 4, 'year', 2015, 'nanosecond', 0, 'hour', 14, ...) called at /usr/lib/perl5/DateTime.pm line 317
    # 	DateTime::_new_from_self('App::Sqitch::DateTime=HASH(0xa4a0488)', 'locale', 'C.UTF-8') called at /usr/lib/perl5/DateTime.pm line 1923
    # 	DateTime::set(undef, 'locale', 'C.UTF-8') called at /root/.cpanm/work/1430288101.16106/App-Sqitch-0.9991/blib/lib/App/Sqitch/DateTime.pm line 63
    # 	App::Sqitch::DateTime::as_string('App::Sqitch::DateTime=HASH(0xa3de0e4)', 'format', 'long') called at t/plan_command.t line 272
    # 
    # Looks like you planned 215 tests but ran 42.
    # Looks like you failed 1 test of 42 run.
    # Looks like your test exited with 255 just after 42.
    t/plan_command.t .... 
    Dubious, test returned 255 (wstat 65280, 0xff00)
    Failed 174/215 subtests 
    t/pragma.t .......... ok
    t/rebase.t .......... ok
    t/revert.t .......... ok
    t/rework.t .......... ok
    t/show.t ............ ok
    t/sqlite.t .......... ok
    t/status.t .......... ok
    t/tag.t ............. ok
    t/tag_cmd.t ......... ok
    t/target.t .......... ok
    t/target_cmd.t ...... ok
    t/upgrade.t ......... ok
    t/verify.t .......... ok
    t/vertica.t ......... ok
    t/x.t ............... ok
    
    Test Summary Report
    -------------------
    t/datetime.t      (Wstat: 65280 Tests: 4 Failed: 1)
      Failed test:  4
      Non-zero exit status: 255
      Parse errors: Bad plan.  You planned 33 tests but ran 4.
    t/item_formatter.t (Wstat: 65280 Tests: 6 Failed: 1)
      Failed test:  6
      Non-zero exit status: 255
      Parse errors: Bad plan.  You planned 158 tests but ran 6.
    t/log.t           (Wstat: 65280 Tests: 45 Failed: 1)
      Failed test:  45
      Non-zero exit status: 255
      Parse errors: Bad plan.  You planned 248 tests but ran 45.
    t/plan_command.t  (Wstat: 65280 Tests: 42 Failed: 1)
      Failed test:  42
      Non-zero exit status: 255
      Parse errors: Bad plan.  You planned 215 tests but ran 42.
    Files=42, Tests=5700, 23 wallclock secs ( 0.77 usr  0.07 sys + 19.62 cusr  1.75 csys = 22.21 CPU)
    Result: FAIL
    Failed 4/42 test programs. 4/5700 subtests failed.
    -> FAIL Installing DWHEELER/App-Sqitch-0.9991.tar.gz failed. See /root/.cpanm/work/1430288101.16106/build.log for details. Retry with --force to force install it.

$ uname -a
Linux corepos-deploy 3.16.0-34-generic #47~14.04.1-Ubuntu SMP Fri Apr 10 17:49:51 UTC 2015 i686 i686 i686 GNU/Linux

**Comment by theory** [comment]
Use of uninitialized value $language in lc at /usr/share/perl5/DateTime/Locale.pm line 246.

Looks like you don’t have locales set up on your box. What’s the output of `echo $LANG`?

**Comment by shantanubhadoria** [comment]
en_SG.UTF-8

**Comment by shantanubhadoria** [comment]
Apologies for the slow reply. I was away for a week.

**Comment by theory** [comment]
Hrm. But Sqitch is setting the DateTime locale to `C.UTF-8`:

    #   DateTime::set(undef, 'locale', 'C.UTF-8') called at /root/.cpanm/work/1430288101.16106/App-Sqitch-0.9991/blib/lib/App/Sqitch/DateTime.pm line 63

@autarch Any idea what can cause DateTime::Locale to lose the language?

**Comment by autarch** [comment]
On Fri, 15 May 2015, David E. Wheeler wrote:

> 
> Hrm. But Sqitch is setting the DateTime locale to C.UTF-8:
> 
> #   DateTime::set(undef, 'locale', 'C.UTF-8') called at /root/.cpanm/work/1430288101.16106/App-Sqitch-0.9991/blib/lib/App/Sqitch/DateTime.pm line 63
> 
> @autarch Any idea what can cause DateTime::Locale to lose the language?

I'm not sure exactly what yo'ure asking. What does "losing the language" 
mean?


-dave

/*============================================================
http://VegGuide.org               http://blog.urth.org
Your guide to all that's veg      House Absolute(ly Pointless)
============================================================*/

**Comment by theory** [comment]
Sorry, I think I pasted the wrong part. Here's the whole, Dave:

    # There were 1 warning(s)
    #   Previous test 3 'as_string_formats should be correct'
    #   Use of uninitialized value $language in lc at /usr/share/perl5/DateTime/Locale.pm line 246.
    #  at /usr/share/perl5/DateTime/Locale.pm line 246.
    #   DateTime::Locale::_guess_id('DateTime::Locale', 'C.UTF_8') called at /usr/share/perl5/DateTime/Locale.pm line 209
    #   DateTime::Locale::load(undef, 'C.UTF-8') called at /usr/lib/perl5/DateTime.pm line 291
    #   DateTime::_set_locale('App::Sqitch::DateTime=HASH(0x9bf514c)', 'C.UTF-8') called at /usr/lib/perl5/DateTime.pm line 230
    #   DateTime::_new('App::Sqitch::DateTime', 'year', 2015, 'second', 13, 'day', 29, 'time_zone', 'DateTime::TimeZone::Asia::Singapore=HASH(0x9bd89cc)', ...) called at /usr/lib/perl5/DateTime.pm line 206
    #   DateTime::new(undef, 'year', 2015, 'time_zone', 'DateTime::TimeZone::Asia::Singapore=HASH(0x9bd89cc)', 'day', 29, 'minute', 15, ...) called at /usr/lib/perl5/DateTime.pm line 317
    #   DateTime::_new_from_self('App::Sqitch::DateTime=HASH(0x9c00d28)', 'locale', 'C.UTF-8') called at /usr/lib/perl5/DateTime.pm line 1923
    #   DateTime::set(undef, 'locale', 'C.UTF-8') called at t/datetime.t line 55

See that `$language` is `undef`. Does DateTime::Locale dislike the C locale?

**Comment by autarch** [comment]
On Tue, 19 May 2015, David E. Wheeler wrote:

> Sorry, I think I pasted the wrong part. Here's the whole, Dave:
> 
> # There were 1 warning(s)
> #   Previous test 3 'as_string_formats should be correct'
> #   Use of uninitialized value $language in lc at /usr/share/perl5/DateTime/Locale.pm line 246.
> #  at /usr/share/perl5/DateTime/Locale.pm line 246.
> #   DateTime::Locale::_guess_id('DateTime::Locale', 'C.UTF_8') called at /usr/share/perl5/DateTime/Locale.pm line 209
> #   DateTime::Locale::load(undef, 'C.UTF-8') called at /usr/lib/perl5/DateTime.pm line 291
> #   DateTime::_set_locale('App::Sqitch::DateTime=HASH(0x9bf514c)', 'C.UTF-8') called at /usr/lib/perl5/DateTime.pm line 230
> #   DateTime::_new('App::Sqitch::DateTime', 'year', 2015, 'second', 13, 'day', 29, 'time_zone', 'DateTime::TimeZone::Asia::Singapore=HASH(0x9bd89cc)
> ', ...) called at /usr/lib/perl5/DateTime.pm line 206
> #   DateTime::new(undef, 'year', 2015, 'time_zone', 'DateTime::TimeZone::Asia::Singapore=HASH(0x9bd89cc)', 'day', 29, 'minute', 15, ...) called at /
> usr/lib/perl5/DateTime.pm line 317
> #   DateTime::_new_from_self('App::Sqitch::DateTime=HASH(0x9c00d28)', 'locale', 'C.UTF-8') called at /usr/lib/perl5/DateTime.pm line 1923
> #   DateTime::set(undef, 'locale', 'C.UTF-8') called at t/datetime.t line 55
> 
> See that $language is undef. Does DateTime::Locale dislike the C locale?

C.UTF-8 is not a valid locale for DateTime::Locale. This code should be 
dying.

I should probably fix that warning, though.


-dave

/*============================================================
http://VegGuide.org               http://blog.urth.org
Your guide to all that's veg      House Absolute(ly Pointless)
============================================================*/

**Comment by theory** [comment]
I don't know where that locale is coming from. Any ideas, @shantanubhadoria?

**Comment by autarch** [comment]
That's the type of locale name you'd find in a shell's `LANG` environment variable.

**Comment by theory** [comment]
This box has `LANG` set to `en_SG.UTF-8` (see above).

**Comment by autarch** [comment]
At https://github.com/theory/sqitch/blob/master/t/datetime.t#L55 you call `POSIX::setlocale( POSIX::LC_TIME() )`, which apparently ends up returning `C.UTF-8`. I'm not sure exactly what's going on there, but I'd guess that this box has `LC_TIME` set to `C.UTF-8`, even though `LANG` is something else.

That all said, the more I look at this, the more I think that DTL should accept `C.UTF-8` and end up giving you the `en_US_POSIX` locale. I think I see the bug causing this problem, but it might take me a little while to fix it. DT::Locale is very difficult to maintain right now.

**Comment by theory** [comment]
That sounds totally reasonable, @autarch, thanks. Would you like me to open an issue in the DTL queue?

**Comment by autarch** [comment]
Sure, go for it. I actually found a way to work on this distro without driving myself too nuts, so I should have a fix out soon.

**Comment by theory** [comment]
[Done](https://rt.cpan.org/Ticket/Display.html?id=104574).
