### ISSUE TITLE
ActivePerl build broken for 5.18 and 5.20

### ISSUE THREAD

**Issue by LightBender** [theory/sqitch#231]
The build is broken on ActivePerl as shown here: http://code.activestate.com/ppm/App-Sqitch/

I don't really know what the problem is since I am not a Perl hacker. But this is a blocking issue since I do not have access to the last working version of ActivePerl (5.16).

Thank you!

**Comment by theory** [comment]
Thanks. I believe I've fixed these issues in 1c6faad4dd6f43fb482915ab732e1415a2b1d9cd and 69614cc54865b8b1efc6ba22fbb9f99f26721cf8. I'll try to get v0.9992 out this week.

**Comment by LightBender** [comment]
Thanks! Looking forward to it!
