### ISSUE TITLE
Interaction with other schema migration tools

### ISSUE THREAD

**Issue by hekevintran** [theory/sqitch#232]
I'm interested in using Sqitch with my Django development.  Django has a feature to handle schema and data migrations, but lacks other aspects of database management.  For example Django does not have a commands for initializing databases, dropping databases, installing extensions, creating indexes beyond the simplest form, etc.  I think Sqitch could fill the role for creating and verifying database objects as long as it's run after Django's migration command is run.

Is this a typical way of using Sqitch?  Do you see any way that this plan will fail?

**Comment by theory** [comment]
I suggest you post your questions to the [mail list](https://groups.google.com/forum/#!forum/sqitch-users), since there it's more likely to be seen by other Django users.
