### ISSUE TITLE
Uninitialized value during `sqitch log`

### ISSUE THREAD

**Issue by FranklinChen** [theory/sqitch#233]
I was following the tutorial at https://metacpan.org/pod/sqitchtutorial with a Mac OS X Homebrew installation of Sqitch with Postgres when I got to

```console
sqitch log db:pg:flipr_test
```

and got, after exiting my pager (`/usr/bin/less`):

```console
Use of uninitialized value $_[1] in pattern match (m//) at /usr/local/lib/perl5/IO/Pager.pm line 98.
```

I don't know if this is technically a bug in Sqitch or in `IO::Pager`.

**Comment by theory** [comment]
IO::Pager, to judge by [the source](https://metacpan.org/source/JPIERCE/IO-Pager-0.34/lib/IO/Pager.pm#L97). It shouldn't use `~` on `$_[1]` unless `$_[1]` is defined.
