### ISSUE TITLE
Registry is at version 1,1 but latest is 1.1.

### ISSUE THREAD

**Issue by steffenmllr** [theory/sqitch#234]
I just upgraded to `sqitch (App::Sqitch) 0.9992` on osx (via homebrew).
On a clean database I can do I `sqitch deploy` which works fine, but when I try to do a `sqitch revert` it shows me:

```
Argument "1,1" isn't numeric in numeric eq (==) at /usr/local/lib/perl5/App/Sqitch/Engine.pm line 980.
Registry is at version 1,1 but latest is 1.1. Please run the "upgrade" conmand
```

when I try to `upgrade` I get:
````
Upgrading registry db:pg://xxxx:@localhost/xxxxx to version 1.1
Argument "1,1" isn't numeric in numeric ne (!=) at /usr/local/lib/perl5/App/Sqitch/Engine.pm line 973.
Argument "1,1" isn't numeric in numeric lt (<) at /usr/local/lib/perl5/App/Sqitch/Engine.pm line 1003.
  * From 1,1 to 1.1
psql:/usr/local/lib/perl5/App/Sqitch/Engine/Upgrade/pg-1.1.sql:3: ERROR:  constraint "changes_script_hash_key" of relation "changes" does not exist
"/usr/local/bin/psql" unexpectedly returned exit value 3
```

Any idea on how to fix the `1.1 !== 1,1` Error ?

**Comment by theory** [comment]
I suspect this line in App::Sqitch::Role::DBIEngine is at fault:

        sprintf '%.1f', $self->dbh->selectcol_arrayref(
            'SELECT MAX(version) FROM releases'
        )->[0];

Is `sprintf` subject to localization here?

**Comment by steffenmllr** [comment]
Yes, my system is in German. Any way to make this localization independent ?

**Comment by theory** [comment]
Does this fix it, @steffenmllr?

    --- a/lib/App/Sqitch/Role/DBIEngine.pm
    +++ b/lib/App/Sqitch/Role/DBIEngine.pm
    @@ -71,6 +71,7 @@ sub _register_release {
 
     sub registry_version {
         my $self = shift;
    +    no locale;
         try {
             sprintf '%.1f', $self->dbh->selectcol_arrayref(
                 'SELECT MAX(version) FROM releases'

**Comment by steffenmllr** [comment]
I installed via homebrew, so let me first find out how to build this thing and come back to you :)

**Comment by steffenmllr** [comment]
ok, brushed up my perl knowledge :) 
unfortunately the fix you described doesn't work. 

It only if I remote the sprintf:
```perl
sub registry_version {
    my $self = shift;
    try {
        return $self->dbh->selectcol_arrayref(
            'SELECT MAX(version) FROM releases'
        )->[0];
    } catch {
        return 0 if $self->_no_table_error;
        die $_;
    };
}
```

**Comment by theory** [comment]
Hrm. What's your locale, @steffenmllr? I'm trying to replicate this issue.

    > LANG=de_DE.UTF-8 perl -MPOSIX=setlocale -E 'setlocale POSIX::LC_ALL, ""; printf "%.1f\n", 1.1223'
    1.1

**Comment by theory** [comment]
Oh, here we go:

    LANG=de_DE.UTF-8 perl -MPOSIX=setlocale -Mlocale -E 'setlocale POSIX::LC_ALL, "de_DE.UTF-8"; printf "%.1f\n", 1.1223'
    1,1

**Comment by theory** [comment]
Seems like `no locale` should work:

    > LANG=de_DE.UTF-8 perl -MPOSIX=setlocale -Mlocale -E 'setlocale POSIX::LC_ALL, "de_DE.UTF-8"; do { no locale; printf "%.1f\n", 1.1223 }'
    1.1

**Comment by steffenmllr** [comment]
Somehow that doesn't work for me, this still prints `1,1` - how does perl pick what to take when `no locale` is set?

**Comment by theory** [comment]
Well, `no locale` should turn off POSIX locales, including numeric locales. What version of Perl are you using?

I'm unable to replicate this in Sqitch itself when I `export LANG=de_DE.UTF-8` unless I also put in a `use locale`. So maybe if we use it then turn it off it will work? Seems weird, but try this:

    --- a/lib/App/Sqitch/Role/DBIEngine.pm
    +++ b/lib/App/Sqitch/Role/DBIEngine.pm
    @@ -71,7 +71,9 @@ sub _register_release {
 
     sub registry_version {
         my $self = shift;
    +    use locale;
         try {
    +        no locale;
             sprintf '%.1f', $self->dbh->selectcol_arrayref(
                 'SELECT MAX(version) FROM releases'
             )->[0];

**Comment by theory** [comment]
With that patch, if I comment-out `no locale` I get the 1,1 behavior. But not if I also comment out `use locale`. :-(

**Comment by steffenmllr** [comment]
I'm using perl `v5.18.2` (`osx 10.10.3` default i guess), activating and deactivating also didn't work.

**Comment by steffenmllr** [comment]
This is my `locale` dump if that helps:
```
LANG="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_CTYPE="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_ALL=
```

**Comment by theory** [comment]
Ah, replicated on 5.18.4. I suspect `no locale` will work on 5.20 or 5.22 (I was using 5.22.0). Will poke at it to try to find a compatible fix.

**Comment by theory** [comment]
Pinging Perl peeps, as `no locale` works on 5.20 but not 5.18. [Gist](https://gist.github.com/theory/a741c258eb20e25cee03).

**Comment by theory** [comment]
That should do it, @steffenmllr, thanks!

**Comment by steffenmllr** [comment]
Thank @theory for a great tool and great support!

**Comment by theory** [comment]
My pleasure, super happy with how it's turning out. :-)
