### ISSUE TITLE
MySQL client variables

### ISSUE THREAD

**Issue by cbandy** [theory/sqitch#236]
It may be possible to support `--set` for MySQL [user variables](http://dev.mysql.com/doc/en/user-variables.html) by [executing some SQL](http://stackoverflow.com/a/10265580/1608057) that uses [`source`](https://dev.mysql.com/doc/en/mysql-batch-commands.html).

**Comment by theory** [comment]
Hrm, it [already uses `source`](/lib/App/Sqitch/Engine/mysql.pm#331), so this should be pretty easy to add.
