### ISSUE TITLE
Can't use another registry database

### ISSUE THREAD

**Issue by guicampos** [theory/sqitch#238]
Hello!
I'm trying to use Sqitch for the first time, and after struggling to make it work on ubuntu 14.04 (and I gave up. I'm running now on Oracle Enterprise Linux), I'm trying to use a schema/database as registry and deploy the changes in another schema/database. But it doesn't work!

My registry schema should be change_manager and the deploy database should be appteste1. The server (tnsname) is orahom.

Here is my config and the following error. I've already tried to drop and recreate the involved schemas, but no deal.

You can view all my sqitch files and configs [here](https://drive.google.com/folderview?id=0BzvVboG75K8zfk5Fc3Z0SV9PMERyQjc5ckxFRWQ4VzJ2RUhHcTd1dFp3a1VfZml5S0MxQXM&usp=sharing), including a list with all perl modules installed.

Perl version is "This is perl, v5.10.1 (*) built for x86_64-linux-thread-multi"

=========== TRY
- Creating the change_manager schema. This should a centralized place for all changes registry.
CREATE USER change_manager identified by 123321 default tablespace users;

- Permission
GRANT DBA TO change_manager;

- Executing create user and grant with a DBA user
$ sqitch deploy --to-change grant_permissions change_manager
Adding registry tables to change_manager
Deploying changes through grant_permissions to change_manager
  + criar_usuario ...... ok
  + grant_permissions .. ok

**Ok! All fine!**

- Now trying to execute the create table with the application's user using the change_manager registry

$ sqitch deploy appteste1
Adding registry tables to appteste1
old   1: CREATE TABLE &registry..releases (
new   1: CREATE TABLE change_manager.releases (
CREATE TABLE change_manager.releases (
*
ERROR at line 1:
ORA-01031: insufficient privileges

/u01/app/oracle/product/12.1.0/dbhome_1/bin/sqlplus unexpectedly returned exit value 7

**It tries to create another registry on the user schema, not in the change_manager schema.**

 What am I doing wrong?

Anyway, I think sqitch is a wonderful tool!

Thanks, 

Guilherme

**Comment by theory** [comment]
On Jul 3, 2015, at 2:27 PM, Guilherme Campos <notifications@github.com> wrote:

> I'm trying to use Sqitch for the first time, and after struggling to make it work on ubuntu 14.04 (and I gave up.

What errors did you encounter on Ubuntu? I’d love to get issues there addressed. Did you use the Debian install instructions from [the home page](http://sqitch.org)?

> I'm running now on Oracle Enterprise Linux), I'm trying to use a schema/database as registry and deploy the changes in another schema/database. But it doesn't work!

What I found as I wrote [the Oracle tutorial](https://metacpan.org/module/sqitchtutorial-oracle) was that I had to schema-qualify all the objects I created, e.g.,

    CREATE TABLE flipr.users (
        nickname  VARCHAR2(512 CHAR) PRIMARY KEY,
        password  VARCHAR2(512 CHAR) NOT NULL,
        timestamp TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL
    );

> My registry schema should be change_manager and the deploy database should be appteste1. The server (tnsname) is orahom.

Yeah, because Sqitch connects as the registry user, that’s going to be the default installation location. Hence the need to schema-qualify your objects. Maybe there’s a way to change the default schema at the top of of your deploy scripts? That’s what I do on PostgreSQL: I add the schema I want to use to the search path:

    SET search_path TO config,public;

Perhaps you can set the current schema in your scripts?

    alter session set current_schema = appteste1;

  http://docs.oracle.com/cd/B28359_01/server.111/b28310/general009.htm#ADMIN02101

Of course, change_manager will need permission to do this.

> It tries to create another registry on the user schema, not in the change_manager schema.
> 
> What am I doing wrong?

You need to always deploy using the change_manager user, never the appteste1 user. Sqitch always assumes you’re connecting as the Sqitch registry user. So it’s up to you to change schemas for your objects in your deploy scripts.

**Comment by guicampos** [comment]
Sorry, I don't have the ubuntu errors logs anymore, but the main problem was to install DBD::Oracle on ubuntu, not installing sqitch. 

Ok, I understand now that I have to use a single DBA user to apply changes and execute the deploy scripts, but if I have more than one database (prod, prod2) and a remote registry database (regdb1, for example), how can I proceed? Will I have to have one registry schema for each production database?

My objective is to have a central registry database (regdb1) to store all changes info and apply the deploy scripts on different databases (prod1, prod2, test1, test2, etc). Is that possible?

Thanks again!

**Comment by theory** [comment]
On Jul 6, 2015, at 12:28 PM, Guilherme Campos <notifications@github.com> wrote:

> Sorry, I don't have the ubuntu errors logs anymore, but the main problem was to install DBD::Oracle on ubuntu, not installing sqitch.

Oh, yeah, that can be a bitch. Took me around a year to get DBD::Oracle to build on my Mac (mostly waiting for 64-bit support from instantclient).

> Ok, I understand now that I have to use a single DBA user to apply changes and execute the deploy scripts, but if I have more than one database (prod, prod2) and a remote registry database (regdb1, for example), how can I proceed? Will I have to have one registry schema for each production database?

Yes.

> My objective is to have a central registry database (regdb1) to store all changes info and apply the deploy scripts on different databases (prod1, prod2, test1, test2, etc). Is that possible?

Not with Oracle, no. It’s an interesting idea, though. And this is the second time in as many days where someone wanted to do something like this. So I’ve added it as a feature request in #241:

  https://github.com/theory/sqitch/issues/241
