### ISSUE TITLE
fe_sendauth: no password

### ISSUE THREAD

**Issue by hack-r** [theory/sqitch#240]
Following Jon Harrington's tutorial, I'm trying to use sqitch with PostgREST (and thus PostgreSQL).

However, when I run sqitch deploy I get the following error:

fe_sendauth: no password supplied

yet I see no option for supplying a password, no option for doing so, and generally no mention of this. Could you point me in the right direction?

I've tried running the command as different users (postgres, root, and a user with database privileges). This issue is also described here: https://stackoverflow.com/questions/31254145/sqitch-throws-fe-sendauth-no-password-error-with-sqitch .

Thanks!

**Comment by theory** [comment]
See [sqitch-passwords](lib/sqitch-passwords.pod) for the various ways to supply passwords.

**Comment by hack-r** [comment]
Ah, awesome! Thank you, David. I think that link is broken but I will mark this as closed and find the resources.

**Comment by theory** [comment]
Yeah, I fixed the link in the comment. Would not have updated your email, of course.
