### ISSUE TITLE
Initalize sqitch database on a new setup for working with existing sqitch.plan

### ISSUE THREAD

**Issue by techniway** [theory/sqitch#245]
Hello

I recently have to reinstall my working environement, and i need to install sqitch and configure it to use my existing sqitch.plan so that i can redeploy all previously made change on this project .
My problem is that after having installed sqitch using cpanm, sqitch show me a database not initialized message when trying to check the status of my project  "sqitch status db:mysql://myuser:mypass@localhost/enlive", 

I know that it's probably a dumb question, but i don't find any answer in the documentation, so can anyone tell me how to initialize my database so that i can continue to work and enjoy sqitch ;) ?

here's a description of my sqitch.plan
[core]
	engine = mysql
	top_dir = httpdocs/sqitch/

[core "mysql"]
	target = dev

[target "dev"]
	uri = db:mysql://myuser:mypass@localhost/maquette

[target "enlive"]
	uri = db:mysql://myuser:mypass@localhost/enlive
	registry = sqitch_enlive
	
[target "newdemo"]
	uri = db:mysql://ip2demo@ip2-demo.com/ip2demo
	
[engine "mysql"]
	target = dev

actually the database enlive and sqitch_enlive are allready created but doesn't contain any tables

**Comment by techniway** [comment]
Nobody :\ ?

**Comment by theory** [comment]
Sqitch will initialize the database when you deploy to it.

However, if you've deployed to this database before, it should of course already be initialized. Is there a `db:mysql://myuser:mypass@localhost/sqitch` database?

**Comment by theory** [comment]
Also, a question like this is more appropriate for the [mail list](https://groups.google.com/forum/#!forum/sqitch-users). GitHub issues are for bug reports and feature requests. Of course, your issue might turn out to be due to a bug, but then you'd be ask to create a GitHub issue once we determined that on the mail list.
