### ISSUE TITLE
Upgrade from 1.0 to 1.1 fails

### ISSUE THREAD

**Issue by kabel-innovu** [theory/sqitch#246]
When attempting to upgrade a repository created by:

    $ sqitch --version
    sqitch (App::Sqitch) 0.9991 

using a newer version:

    $ sqitch --version
    sqitch (App::Sqitch) 0.9992

the following error is generated:

    * From 1.0 to 1.1
    psql:/usr/local/lib/perl5/App/Sqitch/Engine/Upgrade/pg-1.1.sql:3: ERROR:  constraint "changes_script_hash_key" of relation "changes" does not exist

                                 Table "sqitch.changes"
         Column      |           Type           |             Modifiers
    -----------------+--------------------------+------------------------------------
     change_id       | text                     | not null
     script_hash     | text                     |
     change          | text                     | not null
     project         | text                     | not null
     note            | text                     | not null default ''::text
     committed_at    | timestamp with time zone | not null default clock_timestamp()
     committer_name  | text                     | not null
     committer_email | text                     | not null
     planned_at      | timestamp with time zone | not null
     planner_name    | text                     | not null
     planner_email   | text                     | not null
    Indexes:
        "changes_pkey" PRIMARY KEY, btree (change_id)
        "changes_project_script_hash_key" UNIQUE CONSTRAINT, btree (project, script_hash)
     Foreign-key constraints:
        "changes_project_fkey" FOREIGN KEY (project) REFERENCES sqitch.projects(project) ON UPDATE CASCADE
    Referenced by:
        TABLE "sqitch.dependencies" CONSTRAINT "dependencies_change_id_fkey" FOREIGN KEY (change_id) REFERENCES sqitch.changes(change_id) ON UPDATE CASCADE ON DELETE CASCADE
        TABLE "sqitch.dependencies" CONSTRAINT "dependencies_dependency_id_fkey" FOREIGN KEY (dependency_id) REFERENCES sqitch.changes(change_id) ON UPDATE CASCADE
        TABLE "sqitch.tags" CONSTRAINT "tags_change_id_fkey" FOREIGN KEY (change_id)  REFERENCES sqitch.changes(change_id) ON UPDATE CASCADE`

**Comment by theory** [comment]
Did you originally build v0.991 from a Git clone instead of a release? It looks like that patch has already been applied to your code. You can fix it by running these commands:

    ALTER TABLE sqitch.changes DROP CONSTRAINT changes_project_script_hash_key;
    ALTER TABLE sqitch.changes ADD UNIQUE (script_hash);

Then run the the upgrade again.

**Comment by pdl** [comment]
For posterity: this also happens when two deploy sql files are identical in content (this is unusual in practice, as `sqitch add` inserts comments which are unique to each file).

**Comment by theory** [comment]
@pdl Ah-ha. That issue was the reason for the 1.1 upgrade. Prior to that, the script hash had to be unique. 1.1 lets it be the project name and script hash.
