### ISSUE TITLE
Is there a way to use sqitch with in-memory SQLite databases for testing.

### ISSUE THREAD

**Issue by hartzell** [theory/sqitch#248]
Hi,

If a project uses sqitch to set up SQLite databases, is there a way/trick/hack to use apply those scripts to an in-memory SQLite database (e.g. one named ":memory:")?

They're nice for spinning up quickly for tests.

Thanks!

**Comment by theory** [comment]
Alas, no. Each change script is run against a single call to `sqlite3`, which wouldn't work if the database was wiped out after each run (as would be the case with an in-memory database). You might be able to fake it by [memory-mapping a file](https://en.wikipedia.org/wiki/Memory-mapped_file) and using that file for your database.
