### ISSUE TITLE
test fail for SQLite - Registry should no longer need upgrading

### ISSUE THREAD

**Issue by Tux** [theory/sqitch#253]
```
This is perl 5, version 22, subversion 0 (v5.22.0) built for x86_64-linux-thread-multi-ld

$ perl -MV=DBI,DBD::SQLite
DBI
        /pro/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi-ld/DBI.pm: 1.634
DBD::SQLite
        /pro/lib/perl5/site_perl/5.22.0/x86_64-linux-thread-multi-ld/DBD/SQLite.pm: 1.48

t/sqlite.t .......... 1/?
    #   Failed test 'Registry should not need upgrading'
    #   at t/lib/DBIEngineTest.pm line 97.

    #   Failed test 'Registry should no longer need upgrading'
    #   at t/lib/DBIEngineTest.pm line 129.

    #   Failed test 'Registry should not need upgrading'
    #   at t/lib/DBIEngineTest.pm line 152.
    # Looks like you failed 3 tests of 364.
t/sqlite.t .......... 121/?
#   Failed test 'live database'
#   at t/lib/DBIEngineTest.pm line 1733.
# Looks like you failed 1 test of 121.
t/sqlite.t .......... Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/121 subtests

$ prove -vwb t/sqlite.t
t/sqlite.t ..
ok 1 - require App::Sqitch::Engine::sqlite;
ok 2 - config_vars should return three vars
ok 3 - An object of class 'App::Sqitch::Engine::sqlite' isa 'App::Sqitch::Engine::sqlite'
ok 4 - client should default to sqlite3
:
ok 120 - App::Sqitch::Engine::sqlite->can(...)
    # Subtest: live database
    ok 1 - Engine instantiated
    ok 2 - Database should not yet be initialized
    ok 3 - Initialize the database
    ok 4 - Database should now be initialized
    not ok 5 - Registry should not need upgrading
:
    ok 9 - Should have info output for upgrade
    not ok 10 - Registry should no longer need upgrading
:
    ok 17 - Database should be initialized again
    not ok 18 - Registry should not need upgrading
:
    ok 364 - Change ID and script hash should be 77f4c3
    1..364
    # Looks like you failed 3 tests of 364.
not ok 121 - live database

**Comment by theory** [comment]
Huh. Is this consistent? I've not been seeing it in builds on Perl 5.22 on CentOS 7…

**Comment by Tux** [comment]
On Wed, 26 Aug 2015 15:44:14 -0700, "David E. Wheeler"
<notifications@github.com> wrote:

> Huh. Is this consistent? I've not been seeing it in builds on
> Perl 5.22 on CentOS 7…

On *all* my OpenSUSE boxes: 13.1 and 13.2

Do you need more info?

-- 
H.Merijn Brand  http://tux.nl   Perl Monger  http://amsterdam.pm.org/
using perl5.00307 .. 5.21   porting perl5 on HP-UX, AIX, and openSUSE
http://mirrors.develooper.com/hpux/        http://www.test-smoke.org/
http://qa.perl.org   http://www.goldmark.org/jeff/stupid-disclaimers/

**Comment by theory** [comment]
Hrm. I wonder if there's a floating point issue here. Would mind running it again with this patch, @Tux?

    --- a/lib/App/Sqitch/Engine.pm
    +++ b/lib/App/Sqitch/Engine.pm
    @@ -970,6 +970,8 @@ sub latest_change {
 
     sub needs_upgrade {
         my $self = shift;
    +    Test::More::diag("Version: ", $self->registry_version);
    +    Test::More::diag("Release: ", $self->registry_release);
         $self->registry_version != $self->registry_release;
     }

**Comment by Tux** [comment]
FWIW Type::Tiny::XS is not installed

    ok 4 - Database should now be initialized
    # Version: 1.10000000000000009
    # Release: 1.1
    not ok 5 - Registry should not need upgrading

**Comment by theory** [comment]
Yeah, okay, does this patch fix it?

    +++ a/lib/App/Sqitch/Engine/sqlite.pm
    +++ b/lib/App/Sqitch/Engine/sqlite.pm
    @@ -62,6 +62,8 @@ sub name   { 'SQLite' }
     sub driver { 'DBD::SQLite 1.37' }
     sub default_client { 'sqlite3' }
 
    +sub _version_query { 'SELECT ROUND(MAX(version), 1) FROM releases' }
    +
     has dbh => (
         is      => 'rw',
         isa     => DBH,

**Comment by Tux** [comment]
```
$ prove -wl t/sqlite.t
t/sqlite.t .. 4/?     # Version: 1.10000000000000009
    # Release: 1.1

    #   Failed test 'Registry should not need upgrading'
    #   at t/lib/DBIEngineTest.pm line 97.
    # Version: 0
    # Release: 1.1
    # Version: 0
    # Release: 1.1
    # Version: 1.10000000000000009
    # Release: 1.1

    #   Failed test 'Registry should no longer need upgrading'
    #   at t/lib/DBIEngineTest.pm line 129.
    # Version: 1.10000000000000009
    # Release: 1.1

    #   Failed test 'Registry should not need upgrading'
    #   at t/lib/DBIEngineTest.pm line 152.
```

**Comment by theory** [comment]
Well now that's weird. That really should have fixed it.

    sqlite> select round(1.100000009, 1);
    round(1.100000009, 1)
    ---------------------
    1.1

**Comment by theory** [comment]
What about this one (revert the previous one)?

    index 7b10e31..eb13e92 100644
    --- a/lib/App/Sqitch/Role/DBIEngine.pm
    +++ b/lib/App/Sqitch/Role/DBIEngine.pm
    @@ -69,7 +69,7 @@ sub _register_release {
         return $self;
     }
 
    -sub _version_query { 'SELECT MAX(version) FROM releases' }
    +sub _version_query { 'SELECT ROUND(MAX(version), 1) FROM releases' }
 
     sub registry_version {
         my $self = shift;

**Comment by Tux** [comment]
```
t/pg.t .............. 74/? ERROR:  function round(real, integer) does not exist
LINE 1: SELECT ROUND(MAX(version), 1) FROM releases
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
DBD::Pg::db selectcol_arrayref failed: ERROR:  function round(real, integer) does not exist
LINE 1: SELECT ROUND(MAX(version), 1) FROM releases
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
Trace begun at /home/merijn/.cpan/build/App-Sqitch-0.9993-gSrrge/blib/lib/App/Sqitch/Role/DBIEngine.pm line 77
App::Sqitch::Role::DBIEngine::try {...}  at /pro/lib/perl5/site_perl/5.22.0/Try/Tiny.pm line 77
eval {...} at /pro/lib/perl5/site_perl/5.22.0/Try/Tiny.pm line 72
```
```
t/sqlite.t .......... 1/?     # Version: 1.10000000000000009
    # Release: 1.1

    #   Failed test 'Registry should not need upgrading'
    #   at t/lib/DBIEngineTest.pm line 97.
    # Version: 0
    # Release: 1.1
    # Version: 0
    # Release: 1.1
    # Version: 1.10000000000000009
    # Release: 1.1

    #   Failed test 'Registry should no longer need upgrading'
    #   at t/lib/DBIEngineTest.pm line 129.
    # Version: 1.10000000000000009
    # Release: 1.1

    #   Failed test 'Registry should not need upgrading'
    #   at t/lib/DBIEngineTest.pm line 152.
    # Looks like you failed 3 tests of 364.
t/sqlite.t .......... 121/?
#   Failed test 'live database'
#   at t/lib/DBIEngineTest.pm line 1733.
# Looks like you failed 1 test of 121.
t/sqlite.t .......... Dubious, test returned 1 (wstat 256, 0x100)
```

**Comment by theory** [comment]
I don't understand. What does this output?

    echo 'SELECT ROUND(1.10000000000000009, 1);' | sqlite3

**Comment by Tux** [comment]
```
$ echo 'SELECT ROUND(1.10000000000000009, 1);' | sqlite3
1.1
```

**Comment by Tux** [comment]
but if that returns an NV, it is still a FLOAT in longdouble perl

sprintf "%.1f", ... ?

**Comment by theory** [comment]
> perl -MB=svref_2object -MDBI -E 'say  svref_2object \DBI->connect("dbi:SQLite:")->selectcol_arrayref("SELECT ROUND(1.10000000000000009, 1)")->[0]'
    B::NV=SCALAR(0x7fd6db832750)

Crap. Let's try this, then:

    --- a/lib/App/Sqitch/Engine/sqlite.pm
    +++ b/lib/App/Sqitch/Engine/sqlite.pm
    @@ -141,6 +141,8 @@ has _sqlite3 => (
 
     sub sqlite3 { @{ shift->_sqlite3 } }
 
    +sub _version_query { 'SELECT CAST(ROUND(MAX(version), 1) AS TEXT) FROM releases' }
    +
     sub initialized {
         my $self = shift;
         return $self->dbh->selectcol_arrayref(q{

**Comment by Tux** [comment]
I started from a fresh fetch, removing all previous changes
```
All tests successful.
Files=42, Tests=6552, 35 wallclock secs ( 0.61 usr  0.07 sys + 15.45 cusr  1.55 csys = 17.68 CPU)
Result: PASS
```
Glad to have been of help :)

**Comment by theory** [comment]
Thanks. I presume the mysql and pg tests still pass? They must not get NVs from their drivers.

**Comment by theory** [comment]
Oh, BTW, are your Perls using 32-bit floats?

**Comment by Tux** [comment]
$ perl -V:nvsize
nvsize='16';

All tests pass, include all other tests. usually

**Comment by Tux** [comment]
$ perl -V:.*size
charsize='1';
d_chsize='undef';
d_malloc_good_size='undef';
d_malloc_size='undef';
doublesize='8';
fpossize='16';
gidsize='4';
i16size='2';
i32size='4';
i64size='8';
i8size='1';
intsize='4';
ivsize='8';
longdblsize='16';
longlongsize='8';
longsize='8';
lseeksize='8';
nvsize='16';
ptrsize='8';
shortsize='2';
sig_size='69';
sizesize='8';
st_ino_size='8';
u16size='2';
u32size='4';
u64size='8';
u8size='1';
uidsize='4';
uvsize='8';

**Comment by theory** [comment]
Oh, they're big? Mine:

    perl -V:nvsize
    nvsize='8';

**Comment by Tux** [comment]
that is what -Duselongdouble does. And that is why I mentioned that in my initial post
Though I could have been more explicit instead of hoping you knew the meaning of -ld
sorry

**Comment by theory** [comment]
Heh, no problem, it would not have led me to the solution any more quickly, I just would have identified the wrong cause (smaller instead of bigger).

**Comment by theory** [comment]
Bah, yes, got lazy with terminology, thanks.
