### ISSUE TITLE
The MySQL tutorial contains incompatible SQL

### ISSUE THREAD

**Issue by JeffCarpenter** [theory/sqitch#254]
First off, thank you for the promising tool; it addresses a problem that really needs solving. Anyway, onto the details of the report:

Found at https://metacpan.org/pod/sqitchtutorial-mysql

Notes:
* TIMESTAMP does not accept an argument
* client_min_messages does not exist (see SHOW WARNINGS)
* clock_timestamp() does not exist (see CURRENT_TIMESTAMP)
* BIGSERIAL does not exist (see AUTO_INCREMENT)
* TIMESTAMPTZ does not exist

**Comment by theory** [comment]
Hrm. Looks like a bunch of stuff got pasted in from the PostgreSQL tutorial, because the [source code](https://github.com/theory/sqitch-mysql-intro) doesn't have any of that stuff. Looks like it's time to audit the tutorials again. :-(
