### ISSUE TITLE
Deployment flags (Ex sqitch deploy --dev  or sqitch deploy --production)

### ISSUE THREAD

**Issue by MattMorgis** [theory/sqitch#258]
It would be fantastic if there were flags you could set when deploying for development or production. When deploying to a development box, I sometimes want to execute sql scripts that inject some dummy data and have different users/permissions.

**Comment by theory** [comment]
You can set deploy variables and specify them on a per-target basis. Assuming your engine supports variables, that is (currently Postgres, Oracle, Vertica, and SQLite do). Then you check those variables in your scripts.

I'll think about this some more and work on a blog post about it.
