### ISSUE TITLE
engine add command fails with `Can't locate object method "config"`

### ISSUE THREAD

**Issue by wchristian** [theory/sqitch#259]
Call and error:

    vagrant@Debian-jessie-amd64-netboot:~/veure$ sqitch engine add pg veure_test
    Can't locate object method "config" via package "App::Sqitch::Command::engine" at /home/vagrant/perl5/perlbrew/perls/perl-5.18.4/lib/site_perl/5.18.4/App/Sqitch/Command/engine.pm line 88.

sqitch.conf:

    [core]
    	engine = pg
    	top_dir = sqitch

Sqitch version:

    vagrant@Debian-jessie-amd64-netboot:~/veure$ perl -MApp::Sqitch -e 'print App::Sqitch->VERSION'
    0.9993

Not sure if i'm doing something wrong, but this looks like a sqitch bug.

Edit: Forgot to mention: Calling it without any target just works, but results in:

    [engine "pg"]
    	target = db:pg:

**Comment by theory** [comment]
Right, already fixed in f4d75dd. Thanks!

**Comment by wchristian** [comment]
I'd like to ask you to consider a small request: Could you leave patched, but unreleased issues open and tag them as patched? I did search your issues, but did not think to search the closed ones as well, so i thought this had not been reported yet.

Also, any idea on when a release is planned?

**Comment by theory** [comment]
Well, when I pull a commit from a pull request, GitHub immediately closes it.

Dunno when I'll do another release, not actively doing Sqitch stuff at the mo. Probably later this month or early next month.

**Comment by wchristian** [comment]
Thanks for the estimate. :)
