### ISSUE TITLE
MySQL Password Error

### ISSUE THREAD

**Issue by MattMorgis** [theory/sqitch#261]
I am not sure if this is something I am doing wrong or if it is on Sqitch's end. Running on Ubuntu 14.04 with MySQL 5.5. 

I have the password set in ~/.my.cnf, /etc/my.cnf and in the default /etc/mysql/my.cnf. 

When I run `mysql -u root` it logs me into the MySQL console fine. When I run any `sqitch` command from my project's db directory, it gives me: `Access denied for user 'root'@'localhost' (using password: NO)`

Target and Engine are setup as follows:
```
[target "databasename_v1"]
	uri = db:mysql://root@/databasename_v1
[engine "mysql"]
	target = db:mysql://root@/databasename_v1
```

If I change to `db:mysql://root:password@/databasename_v1` it works, but I would ideally not like to have it in my conf file.

**Comment by theory** [comment]
You probably need to install MySQL::Config, as [described in sqitch-passwords](https://github.com/theory/sqitch/blob/master/lib/sqitch-passwords.pod#user-content-Use_a_Password_File). Use `cpan` or `cpanm` to install it:

    cpan MySQL::Config

**Comment by MattMorgis** [comment]
JEEEEZ!! Completely over looked that the link to that. Didn't need to do that on OS X. Fixed everything! Thank you for the reply!
