### ISSUE TITLE
Sqitch on Windows 10 issue

### ISSUE THREAD

**Issue by louis-murray** [theory/sqitch#262]
Hi,

I'm trying to set up Sqitch to work with a localhost MySQL server on my Windows 10 machine. I installed Sqitch through ActivePerl with no issues and I have WAMP set up on my pc. Both are on the same hard drive and in the same directory. MySQL 5.6.17 is what I have currently installed.

 However, when I run `sqitch deploy` from my project's db folder it says 
`adding the registry tables to db:mysql://root:@localhost/sqitch` 
then immediately displays 
`"mysql.exe" failed to start: "The system cannot find the file specified"`

I looked and mysql.exe is definitely in my WAMP directory and I can access my localhost db directly from WAMP without issue so I'm pretty stumped as to what the issue can be.

**Comment by theory** [comment]
Is `mysql.exe` in your path?

**Comment by louis-murray** [comment]
would running `echo %Path%` from command prompt show if it was or not?

**Comment by theory** [comment]
No, but if you just called `mysql` and `mysql.exe` in the command prompt, that would tell us.

**Comment by louis-murray** [comment]
I added it to my path system variable and I still get the same response.

**Comment by theory** [comment]
You added what? The path should not be to the executable, but to the directory that contains it.

What happens when you just run this in a command prompt?

    mysql.exe --version

Or this?

    mysql --version

**Comment by louis-murray** [comment]
I tried to set the path to the bin folder that the executable is in, then out one more to the mysql5.6.17 folder and then out again to the mysql folder and they all returned the below response.

`'mysql' is not recognized as an internal or external command, operable program or batch file.` Is the response i get.

**Comment by theory** [comment]
Then it's not in your path. I suggest you just tell Sqitch where it is and be done with it.

    sqitch config --user engine.mysql.client C:\\path\to\mysql.exe

**Comment by louis-murray** [comment]
Ok, when I add that and run `sqitch deploy` it just brings up all of the options for running mysql. Is there a way to add my username and password to the sqitch.conf so it can make a proper call to mysql? Or is there a better way to go about that?

I appreciate your help.

**Comment by theory** [comment]
I recommend that you read [sqitch-passwords](http://metacpan.org/pod/sqitch-passwords) and [sqitch-configuration](https://metacpan.org/pod/sqitch-configuration).

**Comment by wchristian** [comment]
Brushing this one off with RTFM was a bit unwarranted, as there was an actual bug due to the library used by sqitch to run mysql.exe not being designed very well. #413 has a fix for this if you still can use it, @louis-murray. (Or anyone else who finds this via google.)
