### ISSUE TITLE
Sqitch install forbidden?

### ISSUE THREAD

**Issue by calebmer** [theory/sqitch#263]
I'm trying to setup Sqitch on my development machine, but it will not install. I am running on OS X Mavericks and using homebrew. Specifically, I ran: `brew tap theory/sqitch` followed by `brew install sqitch_pg` to which homebrew failed with the following log:

```
curl: (22) The requested URL returned error: 403 Forbidden
Error: Failed to download resource "sqitch"
Download failed: http://cpan.cpantesters.org/authors/id/D/DW/DWHEELER/App-Sqitch-0.9993.tar.gz
```

**Comment by theory** [comment]
http://cpan.cpantesters.org is down. Pinging maintainers…

**Comment by ehuelsmann** [comment]
This might explain it: http://blog.cpantesters.org/

Regards,

Erik.

**Comment by theory** [comment]
Should be working now (and for a while now…).
