### ISSUE TITLE
Install PREFIX for etc directory is not the same as the rest of the distribution

### ISSUE THREAD

**Issue by carragom** [theory/sqitch#264]
When I try to install Sqitch with:

    cpanm App::Sqitch

It install most files under the `/usr/local` PREFIX as expected. But the `etc` directory gets incorrectly installed under `/usr/etc` instead of `/usr/local/etc`. Any idea why the `/usr/local` PREFIX is not honored in this case?. How does the package figures out where should the `etc` directory go?.

In my system (Debian 8) there is no need to be root in order to install Perl packages, the staff group has all the permissions required to do it. But in this case, the installation fails due to permission problems because Sqitch is trying to write to `/usr/etc` instead of `/usr/local/etc`.

Thanks for your time.

**Comment by theory** [comment]
It uses `--etcdir` if you pass it to `Build.PL`. Which of course `cpanm` won't. Otherwise it tries to use the prefix or install base defined by the installer. If none of those are set, it falls back on the prefix your Perl was built in. Run this to see what it is:

    perl -MConfig -E 'say $Config{prefix}'

**Comment by carragom** [comment]
Thanks a lot for the quick response. Great to know it can be controlled with `--etcdir`. And yes, in my system `$Config{prefix}` does point to `/usr` so that explains the behavior.

Just one thought, for the rest of the paths, the installer apparently uses the site version of the config for example (`$Config{siteman3dir}` instead of `$Config{man3dir}`) and the same goes for `$Config{sitelib}`, `$Config{sitearch}` etc.

Would'n it make more sense to default to `$Config{siteprefix}` instead of `$Config{prefix}` for the `etc` directory too?.

**Comment by carragom** [comment]
According to [Module::Build](https://metacpan.org/pod/Module::Build#INSTALL-PATHS) the default `installdirs` is effectively `site`.

**Comment by theory** [comment]
See #265 for further work on this issue.
