### ISSUE TITLE
Bug in engine.pm

### ISSUE THREAD

**Issue by adunstan** [theory/sqitch#267]
[andrew@ad-f22 sqtest]$ sqitch engine add pg sqtest
Can't locate object method "config" via package "App::Sqitch::Command::engine" at /home/andrew/perl5/lib/perl5/App/Sqitch/Command/engine.pm line 88.

Looks like this line should refer to $self->sqitch->config rather than to $self->config

At any rate that seemed to fix it for me.

**Comment by theory** [comment]
Dupes #259, was fixed in f4d75dd. Thanks!

**Comment by theory** [comment]
Er, also #255. Guess I should do a release soon.

**Comment by austinrivas** [comment]
+1 on releasing this fix soon, great library btw

**Comment by theory** [comment]
Done, v0.9994 has been released!
