### ISSUE TITLE
Test failures with -Duselongdouble

### ISSUE THREAD

**Issue by eserte** [theory/sqitch#270]
Statistical analsysis shows a high probability of test failures with perls compiled with -Duselongdouble: http://analysis.cpantesters.org/reports_by_field?distv=App-Sqitch-0.9993;field=conf%3Auselongdouble

**Comment by theory** [comment]
Thanks. Merijn helped me sort this out a while ago, and I fixed it in dcbbe6da. Yes, I'm overdue for a release. :-)
