### ISSUE TITLE
Registry is at version 0 but latest is 1.1. Please run the "upgrade" conmand

### ISSUE THREAD

**Issue by arnaldop** [theory/sqitch#271]
I ran a command from shell history:

    sqitch revert -y && sqitch --verbose deploy --mode change

I had just dropped all objects including the Sqitch schema, so the database was blank.

I sa #234 but my message is slightly different:

    Registry is at version 0 but latest is 1.1. Please run the "upgrade" conmand

Please advise. For now the fix is to not run revert on an empty database.

Thanks!

**Comment by theory** [comment]
Are you using SQLite? If so, [this commit](https://github.com/theory/sqitch/commit/dcbbe6da297eb2c6850e3a308c78dcfca1693ffd) might address the issue.

**Comment by arnaldop** [comment]
No, I'm on Postgres.
Thanks!

On Wed, Nov 18, 2015 at 11:48 AM, David E. Wheeler <notifications@github.com

**Comment by theory** [comment]
This error happens when sqitch finds no registry schema objects. Without them, you cannot revert. Sqitch uses the registry to decide what to revert. Since you dropped them, it thinks that the registry is out-of-date. I'll improve it to detect when the registry simply isn't there. Meanwhile, to fix your issue, you'll have to revert all your changes yourself, or else drop the whole database and create a new one.

**Comment by arnaldop** [comment]
That's fine. I just figured the fix you just described would be a more
robust behavior for the app. I worked around it, though. Thanks again!

**Comment by EmilGerth** [comment]
This error also occurs if the account Sqitch is using does not have permission to the `sqitch` schema in Postgres (maybe others, too). Found this thread searching that error, and my solution ended up being those permissions. Important to note this error implies not having USAGE on sqitch - you will get a more specific "permission denied on relation" message if you are missing table access.

The quickest solution is to just make the account running your deployment owner of the database. `ALTER DATABASE database OWNER TO role;`
