### ISSUE TITLE
<hash>~ not recognized

### ISSUE THREAD

**Issue by adunstan** [theory/sqitch#272]
sqitch verify --from-change <hash>~ runs the verify script for the change <hash> as well as what follows it.

**Comment by theory** [comment]
What?

**Comment by adunstan** [comment]
This has happened to me several times. If I want to verify from the change following foo, if I specify --from-change foo~ where foo is the change's sha1 signature, it also run's foo's verify script. Does the ~ suffix not work with sha1 change designators? If so, it should, (c.f. git).

**Comment by theory** [comment]
`^` should work. See [sqitchchanges](http://metacpan.org/pod/sqitchchanges).

**Comment by adunstan** [comment]
I did see sqitchchanges. I filed the bug because for me it's NOT working.

**Comment by theory** [comment]
Oh, I forgot that `~` was in there. It is not the same as in Git. I agree it should not run foo's script.

**Comment by theory** [comment]
Thanks so much for reporting this, Andrew. I never use the `verify` command, so never would have noticed this inconsistency on my own. :-)
