### ISSUE TITLE
passing mysql option - defaults-group-suffix

### ISSUE THREAD

**Issue by tduerr** [theory/sqitch#273]
We're trying to the mysql command line option --defaults-group-suffix.

/usr/bin/mysql --defaults-group-suffix=X 

This option allows us to specify multiple username/passwords in my.cnf.
We neeed this because we're trying to run sqitch from a central Jenkins server.

We've tried aliasing the mysql command and referencing a bash script in sqitch.conf client 
command.

It doesn't seem to be passed. Not sure if this should work or if I'm missing something.

Thanks,
Tom

**Comment by theory** [comment]
You should are able to use a shell script that adds its args to that call to MySQL. Something like

    /usr/bin/mysql --defaults-group-suffix=x $@

Then set `core.client` or `mysql.client` to point to that script. Make sure it's executable!

**Comment by tduerr** [comment]
Dave, 
Thanks for the response.

Still hitting issues.   

Running sqitch deploy results in a mysql usage error.

Here is relevant info. 


-- mysql script (/home/.../mysql2) . Its executable 
/usr/bin/mysql --defaults-group-suffix=X $@


-- sqitch conf
[core]
    engine = mysql
[engine "mysql"]
    client =/home/.../mysql2
[deploy]
	verify = true
[rebase]
	verify = true


$ sqitch deploy --target db:mysql://test@172.17.0.2/loyalty 
Adding registry tables to db:mysql://test@172.17.0.2/sqitch
/usr/bin/mysql  Ver 14.14 Distrib 5.5.46, for debian-linux-gnu (x86_64) using readline 6.3
Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Usage: /usr/bin/mysql [OPTIONS] [database]
  -?, --help          Display this help and exit.
  -I, --help          Synonym for -?
  --auto-rehash       Enable automatic rehashing. One doesn't need to use
                      'rehash' to get table and field completion, but startup
                      and reconnecting may take a longer time. Disable with
                      --disable-auto-rehash.
                      (Defaults to on; use --skip-auto-rehash to disable.)
  -A, --no-auto-rehash 
                      No automatic rehashing. One has to use 'rehash' to get
                      table and field completion. This gives a quicker start of
                      mysql and disables rehashing on reconnect.
  --auto-vertical-output 
                      Automatically switch to vertical output mode if the
                      result is wider than the terminal width.
  -B, --batch         Don't use history file. Disable interactive behavior.
                      (Enables --silent.)
Default options are read from the following files in the given order:
/etc/my.cnf /etc/mysql/my.cnf /usr/etc/my.cnf ~/.my.cnf 
The following groups are read: mysql client mysqlX clientX
The following options may be given as the first argument:
--print-defaults        Print the program argument list and exit.
--no-defaults           Don't read default options from any option file.
--defaults-file=#       Only read default options from the given file #.
--defaults-extra-file=# Read this file after the global files are read.

.
.

.  
"/home/.../mysql2" unexpectedly returned exit value 1

**Comment by theory** [comment]
It's "David".

I sure as hell wish MySQL would emit an error saying what argument it disliked. :-1:

Try running this:

    /home/../mysql2 --defaults-group-suffix=X --username test --database sqitch --host 172.17.0.2 --silent --skip-column-names --skip-line-numbers

If you get the error, try removing options till you figure out which one MySQL dislikes.

**Comment by tduerr** [comment]
David,

It doesn't like "username". It wants "user" instead. 

Thanks,
Tom

**Comment by theory** [comment]
Sorry, that was a typo on my part. It works with `--user`?

**Comment by tduerr** [comment]
Yes.
tduerr@tom-MBP-X$ more mysql2.sh
/usr/bin/mysql --defaults-group-suffix=X --user test --host 172.17.0.2 --database loyalty  --silent --skip-column-names --skip-line-numbers 

tduerr@tom-MBP-X$ ./mysql2.sh
mysql>

**Comment by theory** [comment]
Please set `mysql2.sh` to just this:

    /usr/bin/mysql --defaults-group-suffix=X "$@"

Note that I've added quotation marks around `$@`, per [this SO answer](http://stackoverflow.com/a/3190826/79202). Then run

    ./mysql2.sh --user test --host 172.17.0.2 --database loyalty --silent --skip-column-names --skip-line-numbers

**Comment by tduerr** [comment]
The quotes around $@ solved the problem. 
Its working now.

Thanks!

**Comment by theory** [comment]
Great!!
