### ISSUE TITLE
sqitch-target documentation indicates --set option, command does not recognize it

### ISSUE THREAD

**Issue by clad** [theory/sqitch#274]
Documentation bug? I've been trying to add target specific deploy vars without success. From man sqitch-target:

   "add"
       Add a target named "<name>" for the database at "<uri>". The "--set" option specifies target-specific properties. 

What I get:
$ sqitch target add test "db:pg:test" --set yo=stellar
Unknown option: set

I hope I'm just missing the syntax, because it'd be really nice to have per target vars in sqitch.conf.

**Comment by theory** [comment]
Sorry, `--set` got removed; guess I missed a mention in the docs. Use `--uri`, `--top-dir`, etc. to set target properties.

`--set` will be restored to add client variables at some point.

**Comment by theory** [comment]
Created #275 as a to-do to make `--set` useful.
