### ISSUE TITLE
Best practice question regarding the removal of old tables

### ISSUE THREAD

**Issue by tonylukasavage** [theory/sqitch#277]
> NOTE: I'm not gonna get into the specifics of our DB since this applies at a higher level in terms of best practices for sqitch. I'll provide them if it becomes necessary.

So we're using sqitch, have been for a while and it's working great. I'm at a point where I need to DROP a few tables that are no longer in use. The `deploy` script for this is simple enough, but I was wondering what an appropriate `revert` script would be for such an operation? I couldn't think of a clear way to revert this without recreating the whole table from a backup of it, which is obviously highly impractical. 

What's the suggested method here? Is there an entirely different approach I'm unaware of for dealing with this situation? Any help would be great.

If this is an inappropriate place for this discussion, please let me know and I'll move it elsewhere.

**Comment by theory** [comment]
One way to do it would be to rename the old table, instead, and not drop it. You can always drop it manually later (or in a later deployment) once you're comfortable with it being dead for good.

I suggest posting to the [mail list](https://groups.google.com/forum/#!forum/sqitch-users) for a broader audience of possible opinions. :-)
