### ISSUE TITLE
A target passed after a change on the command-line is ignored

### ISSUE THREAD

**Issue by zeha** [theory/sqitch#281]
Hi,

we're using per-developer accounts in PostgreSQL, and as such having a shared sqitch.conf in VCS is a bit troublesome. We'd like to use the `service=foo` libpq option to read user/password (etc.) from ~/.pg_service.conf instead.

Thanks,
Christian

**Comment by theory** [comment]
What does that look like on the command-line when calling `psql`?

Also note that you can put users-specific targets in `~/.sqitch/sqitch.conf`.

**Comment by zeha** [comment]
It's just `psql service=foo`.

Oh, I tried putting user-specific targets into `~/.sqitch.conf`, but that's obviously the wrong file!

**Comment by theory** [comment]
Yeah, run this command:

    sqitch config --user user.email $youremailaddress

That will write to the file you want. The [target command](/theory/sqitch/blob/master/lib/sqitch-target.pod) currently only writes to the project `sqitch.conf` file, but you can cut and paste them to the user file.

**Comment by theory** [comment]
Looks like sqitch already supports libpq targets. Just put the params in the query string part of the [database uri](/theory/uri-db/). For example, I put this into my `~/.pg_service.conf`:

    [foo]
    dbname=configuration

Then I was able to create a target in my `sqitch.conf` like this:

    sqitch target add foo 'db:pg:?service=foo'

And then it worked:

    sqitch status foo                         
    # On database foo
    # Project:  configuration
    # Change:   1685a063610a3e982b32478da2f110349a29af47
    # Name:     insert_txns
    ...

Looks like there might be a bug in the target-handling for some commands, though:

    sqitch revert @HEAD^ foo   
    warning: Too many targets specified; connecting to local

I'll have to look into that.
