### ISSUE TITLE
How to update an extension

### ISSUE THREAD

**Issue by jmarca** [theory/sqitch#284]
I'm new to sqitch so apologies if this has already been hashed out, and apologies if issues isn't the right place to ask questions like this.

Anyway, following along with the PostgreSQL example, and I want to add postgis extension, in a similar manner to how the pgcrypto extension was added in the tutorial.

That's all fine, but what I'm wondering if there is a convention-ed way to set up future upgrades.  From the [PostGIS docs](http://postgis.net/docs/postgis_installation.html#soft_upgrade_extensions), one can do something like:

```
ALTER EXTENSION postgis UPDATE TO "2.2.2devnext";
ALTER EXTENSION postgis_topology UPDATE TO "2.2.2devnext";
```

So to my new-ish understanding of sqitch, what I would do when the next release of postgis comes out is to tag my repo, then do something like:

```
sqitch rework postgis_extension -n 'upgrade postgis extensions.'
```

And then use that `alter extension ... update... ` command in the new "deploy" command.

Is that about correct?  Or is there a dependency upgrade command, and I can just depend on postgis@version or something similar?

**Comment by theory** [comment]
Yep, that's exactly what I would do, especially if I then wanted to add other changes dependent on new features in the new version.

BTW, you might want to subscribe to the [mail list](https://groups.google.com/forum/#!forum/sqitch-users) and post questions there.

**Comment by jmarca** [comment]
Thanks for the link to the mail list.  I missed that.
