### ISSUE TITLE
Sqitch revert is not consistent with git revert

### ISSUE THREAD

**Issue by eric-brechemier** [theory/sqitch#286]
When using `git revert`, only the target commit is reverted. When using `sqitch revert`, all changes after the target change are reverted, excluding the target change.

I found that the actual behavior of sqitch is made more explicit by using the flag `--to` all the time, although it has no added effect:

```
sqitch revert --to `target/change`
```

and that the operator `^1` can be used to get closer to what I expect:

```
sqitch revert `target/change^1`
```

but still, all changes deployed after the target change are reverted as well, whether or not dependencies have been declared explicitly on this change.

**Comment by theory** [comment]
Sqitch's `revert` command is more like Git's `reset` command than `revert`. There is no way in Sqitch to remove a change, short of:

1. Reverting to the change just before that change `--to change^`
2. Removing that change from the plan (requires editing the plan file and deleting the relevant line).
3. Deploying again

Happy to answer questions and explain things, though the [mail list](https://groups.google.com/forum/#!forum/sqitch-users) might be a better forum for that.

**Comment by eric-brechemier** [comment]
It is more a comment than a question, so I am fine with your closing the issue.

I have been using `sqitch` for a few months now and I wanted to report this fact which made my learning curve a bit steeper than it might be.

Short of changing the default behavior of `sqitch revert` to roll the plan back `--to` the change just before the one given, which would break the tool for existing users, I merely thought that adding a new option `--before change` as an alias for `--to change^1` might bring the difference into light, if only for people who read the documentation.

**Comment by theory** [comment]
Or maybe a comment in the docs that says, "If you're a git user thinking this is like `git revert`, it's not, it's more like `reset`?

**Comment by eric-brechemier** [comment]
I am not actually sure that `git reset` is the right analogy. It is typically used to unstage changes that have not been committed yet (the usage suggested by `git status`: `use "git reset HEAD <file>..." to unstage`), while `sqitch revert` applies revert scripts to cancel changes that have already been committed to the database, very much like `git revert`.

So `sqitch revert` is actually quite like `git revert` with two major differences:

* it reverts every single change back to the target
* it does not revert the target itself, but stops on the target

I would rather say that `git reset` is similar to `sqitch revert --log-only`, but that's not going to help newcomers much :)

**Comment by eric-brechemier** [comment]
The best analogy I found is:

> If you're a git user thinking this is like `git revert`, sorry it's not. `sqitch revert` is more like time travel. It takes your database back to the state it had just after applying the target change. It feels like magic, but it's actually all the time you spent writing revert scripts that finally pays off. Starting from the last change currently deployed, `sqitch revert` runs each revert script in turn until the target change is reached and becomes the last change deployed.

**Comment by theory** [comment]
Thanks for that!
