### ISSUE TITLE
DOCS: Add section for recommended practices

### ISSUE THREAD

**Issue by decibel** [theory/sqitch#291]
The tutorial is a nice basic intro and the docs are nicely comprehensive, but I'm discovering that there's a bunch of use patterns that really impact the usability of the tool. Things like

- CREATE vs CREATE OR REPLACE (matters for rework)
- What to name changes (seems like you want some pattern like FUNCTION_schema_name.function_name
- Probably a ton of other things I haven't figured out yet

Maybe this is better as a wiki so it's easier for others to add to it. Or make it a doc page and encourage people to submit changes by providing a direct link to the source and pointing them at the edit button...

**Comment by theory** [comment]
Any reason not to start that stuff in [/sqitch/wiki](/sqitch/wiki)?

**Comment by decibel** [comment]
Sounds good to me.
