### ISSUE TITLE
sqitch remove

### ISSUE THREAD

**Issue by decibel** [theory/sqitch#295]
Sometimes you sqitch add and then go "crap, not what I wanted". It'd be nice if there was an easy way to undo that. To start with, I think supporting only "sqitch remove --last" would be OK. Presumably it shouldn't let you remove across a tag boundary.

(See related request for rename command: #290)

**Comment by theory** [comment]
I do this all the time. I just

    git checkout .
    git clean -dfx

**Comment by decibel** [comment]
That's assuming there's nothing else in the checkout you want to keep, 
which isn't always the case.

**Comment by mmonroe86** [comment]
I  second @decibel  on this. It would be nice to have a sqitch remove command to quickly undo an unwanted sqitch add

**Comment by theory** [comment]
Duplicates #53.
