### ISSUE TITLE
Sqitch tutorial:  Are 'verify/*.sql' examples out-of-date?

### ISSUE THREAD

**Issue by jkeenan** [theory/sqitch#298]
I am working my way through the Sqitch tutorial at https://metacpan.org/pod/sqitchtutorial, App::Sqitch-0.9994.  I'm at the point where I'm issuing a command like this:
```sh
sqitch add flips -r appschema -r users -n 'Adds table for storing flips.'
```
When I open up the `verify/flips.sql` for editing, I see this:
```
$ cat verify/flips.sql 
-- Verify flipr:flips on pg

BEGIN;

-- XXX Add verifications here.

ROLLBACK;
```
The tutorial, however, prompts me to expect `COMMIT;` where you see `ROLLBACK;` above.

Is the tutorial correct or is it out-of-date?

Thank you very much.
Jim Keenan

**Comment by theory** [comment]
Laggards from earlier revisions, thanks for the catch!
