### ISSUE TITLE
docker image broken?

### ISSUE THREAD

**Issue by greaber** [theory/sqitch#303]
Am I using it wrong?
```
$ docker run --rm docteurklein/sqitch:pgsql init flipr --url https://github.com/theory/sqitch-intro/ --engine pg                                                   
init: 1: init: [sqitch]: not found
```

**Comment by theory** [comment]
I've not built a docker image for Sqitch, so I've no idea. I think maybe you'd be better off asking @docteurklein?

**Comment by greaber** [comment]
OK, it is mentioned in the docs, so I thought you might know, but I will pursue it with him or her.

**Comment by greaber** [comment]
Unless he answers here first.

**Comment by greaber** [comment]
Looks like the Dockerfile is very simple:

```
FROM perl:latest
RUN cpan App::Sqitch
RUN cpan DBD::Pg
VOLUME [/src]
WORKDIR /src
ENTRYPOINT [sqitch]
```

**Comment by docteurklein** [comment]
@greaber I'll try to find out what's wrong.

**Comment by docteurklein** [comment]
@greaber a temporary workaround is:

     docker run --rm -it --entrypoint /usr/local/bin/sqitch docteurklein/sqitch:pgsql

**Comment by docteurklein** [comment]
@greaber @theory it should be good now.

**Comment by docteurklein** [comment]
see https://github.com/docteurklein/docker-sqitch/commit/086685a9a8477f8c2b7b33e20f7416ad503af6af

**Comment by theory** [comment]
Hey, this is awesome. Can I link to your project in the installation section of the Sqitch site, @docteurklein?

**Comment by docteurklein** [comment]
@theory my pleasure :) Unless I'm wrong, there is already a section about docker referencing it.
Otherwise, no problem, I'd be glad if you do.

**Comment by theory** [comment]
Oh. Oh yeah. Well then never mind. :-)

**Comment by greaber** [comment]
Thanks!

**Comment by greaber** [comment]
Maybe you should also include instructions about necessary volume mounts.  I was able to make sqitch work as follows:
```
$ alias sqitch='docker run -v $HOME:/root -v $(pwd):/src --rm docteurklein/sqitch:pgsql'
```
This assumes, of course, that sqitch doesn't need to access the filesystem except for your home directory and the working directory.

**Comment by theory** [comment]
Care to submit a PR to the gh-pages branch?

**Comment by greaber** [comment]
Actually, I realize now there are some other issues with using the docker image effectively.  If I sort them all out, I will.

**Comment by theory** [comment]
Awesome, thank you!

**Comment by greaber** [comment]
Maybe this is just my lack of understanding of sqitch, but I couldn't get the docker image to work because `psql` wasn't installed.  I made the following Dockerfile:

````
FROM docteurklein/sqitch:pgsql
RUN apt-get update && apt-get install -y postgresql-client
```

Then I built an image from it with:

```
docker build -t sq .
```

If psql is really necessary then it should be included in the image the docs recommend.

Then I ran postgres and set up some aliases:

```
docker run --name=pg -d postgres
alias createdb='docker run --rm --link=pg -e PGHOST=pg -e PGUSER=postgres postgres createdb'
alias psql='docker run -it --rm --link=pg -e PGHOST=pg -e PGUSER=postgres postgres psql'
alias sqitch='docker run --rm --link=pg -e PGHOST=pg -e PGUSER=postgres -v $HOME:/root -v $(pwd):/src sq'
```

Then (after waiting a few seconds for postgres to be ready), I was able to go through some of the initial steps of the tutorial:

```
createdb flipr_test
sqitch deploy db:pg:flipr_test
```

So, it seems to work so far, but there may be further glitches, and I haven't tried any database engines other than postgres.  Also, one annoyance with docker is that all the files it creates are owned by root.  A way around this is described here: http://stackoverflow.com/questions/27925006/using-host-environment-variables-with-dockerfile

I guess there should be a slicker process and one that works not just for postgres before it makes sense to recommend docker as a way of running sqitch to people who don't know what they're doing.

**Comment by docteurklein** [comment]
@greaber thanks for the clear explanations.
There might still be a lot of problems with this docker image as it wasn't tested very thoroughly.
The fact it was missing the postgres-client might be the best example of what is still missing.
If you have the time, you could make a PR on https://github.com/docteurklein/docker-sqitch/blob/master/pgsql/Dockerfile.
Otherwise, I'll try to find time to do it.

Concerning the file permissions, this is a known "problem" with docker, that could be resolved in many ways.
One of the easiest to me is to use [`--user`](https://docs.docker.com/engine/reference/run/#user):


    docker run --rm -it --user 1000:1000 -v $HOME:/root -v $(pwd):/src docteurklein/sqitch:pgsql init test

**Comment by greaber** [comment]
OK, I made a pull request for the image.  Thanks for the simpler fix for the root user issue.

**Comment by docteurklein** [comment]
thanks! merged https://github.com/docteurklein/docker-sqitch/pull/4
