### ISSUE TITLE
Running "sqitch add" or "sqitch add help" return nasty errors

### ISSUE THREAD

**Issue by deinspanjer** [theory/sqitch#305]
```
$ sqitch add
Use of uninitialized value $name in exists at /usr/local/lib/perl5/site_perl/5.24.0/App/Sqitch/Plan.pm line 897.
Use of uninitialized value $name in pattern match (m//) at /usr/local/lib/perl5/site_perl/5.24.0/App/Sqitch/Plan.pm line 898.
Use of uninitialized value $name in pattern match (m//) at /usr/local/lib/perl5/site_perl/5.24.0/App/Sqitch/Plan.pm line 903.
"{name}" is invalid: changes must not begin with punctuation, contain "@", ":", "#", or blanks, or end in punctuation or digits following punctuation
$ sqitch add help
"vi /tmp/8kWidySj4f" failed to start: "No such file or directory"
```

I eventually got it right and did "sqitch help add", but it might be good to return a better error.

**Comment by theory** [comment]
Hrm. Not able to duplicate. I get the proper error message:

    > sqitch add
    Usage:
          sqitch [options] add [change options] [<template options>] <change> [<target>]

    Options:
            -c --change               name of the change to add
            -r --requires             require change
            -x --conflicts            declare conflicting change
            -a --all                  add change to all project plans
            -s --set                  set a template variable
            -n --note                 a note describing the change

            -t --template             name of the templates to use
               --template-directory   path to directory containing templates
               --use [template=path]  path to named template

               --with    [script]     create named script
               --without [script]     do not create named script
            -e --edit, --open-editor  open change scripts in an editor

There are a bunch of fixes for the `add` command in v0.9995; maybe one of them fixed this issue?

…

Yep, I ran it with the v0.9994 release and got the errors you got. So I think it's fixed!
