### ISSUE TITLE
Fails with DateTime 1.29+

### ISSUE THREAD

**Issue by andk** [theory/sqitch#308]
As per subject. Sample fail report with 1.33:

http://www.cpantesters.org/cpan/report/70720770

Downgrading to 1.28 does as a workaround.

HTH&&Thanks,

**Comment by theory** [comment]
Was fixed in #304, thanks to Rolsky, I just haven't released it yet. I sure appreciate all the work you do chasing stuff down like this, so I'm sorry you had to spend the time digging into something fixed but unreleased, @andk.

**Comment by andk** [comment]
np, better one report too many than one too few. Thanks!
