### ISSUE TITLE
Running sqitch deploy with different databases on the same MySQL server

### ISSUE THREAD

**Issue by srinikandula** [theory/sqitch#313]
I have about 5 different databases on the same MySQL server on to which I plan run the sqitch migration scripts. These databases represent various environments i.e. dev, testing, staging etc. 
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| staging |
| device_graph       |
| flipr_test         |
| mysql              |
| testing              |
| performance_schema |
| sqitch             |
| sys                |
+--------------------+

After I install the migrations to one database using the below command 

`>sqitch deploy db:mysql://root@/flipr_test`

and when I try to deploy the changes to the other database it does not seem recognize the new database

```
>sqitch deploy db:mysql://root@/device_graph
Nothing to deploy (up-to-date)
```
I think the changes are recorded in the database 'sqitch' but it doesn't seem to recognize the database name in the URI. How can I successfully install migration on to different database?

**Comment by theory** [comment]
Sqitch records database deployment in a registry database. By default this database is named "sqitch". If you want to deploy the same sqitch plan to multiple databases on a single MySQL instance, you can specify a different registry database for each. For ad-hoc databases, just pass a registry URI via the `--registry` option, something like:

    sqitch deploy db:mysql://root@/device_graph --registry db:mysql://root@/sqitch_device_graph

If you record each target in the project configuration via the [target command](/theory/sqitch/blob/master/lib/sqitch-target.pod), you can configure a registry for each target there, like so:

    sqitch target add device_graph --uri db:mysql://root@/device_graph --registry db:mysql://root@/sqitch_device_graph

Thereafter, you can just deploy to that database by name:

    sqitch deploy device_graph

HTH. BTW, in the future consider posting questions to the [mail list](https://groups.google.com/forum/#!forum/sqitch-users); I try to reserve issues for bugs and feature requests. Thanks!

**Comment by srinikandula** [comment]
Sure. Thank you.
