### ISSUE TITLE
Sqitch deploy fails after rework with minimal change

### ISSUE THREAD

**Issue by kboucher** [theory/sqitch#317]
I am trying to add some updates that were missed in a previous changeset to our sqitch implementation using `rework` but am receiving the following error when running `sqitch deploy`:

`ERROR:  duplicate key value violates unique constraint "changes_project_script_hash_key"`

In this particular case, two lines were added to the `deploy` script, one line added to the `revert` script and the  and `verify` script was left unchanged.

Shouldn't this be enough for the hash to be different?

**Comment by kboucher** [comment]
Turns out I had three functions in the file, but was only updating two of them. Once I deleted the unchanged function from the file, all was well.

So, I'm guessing the hashing algorithm works at the function level, rather than the file level.

**Comment by theory** [comment]
No, it works [at the file level](/theory/sqitch/blob/master/lib/App/Sqitch/Plan/Change.pm#L218). Not sure why it though it was unchanged for you…

**Comment by ra1fee** [comment]
This may happen if you fail to save the file before deploy as well. Just an FYI for fellow noobs out there. 😳

**Comment by fbrcode** [comment]
I'm having the same issue apparently and it's blocking me to move forward with the research on migration tools. I really liked sqitch and would be able to get around it (not by manual process).

I was just following the tutorial and had this issue:

This is the detailed view of what I'm facing:
<img width="1645" alt="image" src="https://user-images.githubusercontent.com/52377300/207927547-4f1f96b6-d903-45c2-a708-72aeb575c33c.png">
