### ISSUE TITLE
Multiple Values Error in GitLike when doing a sqitch add

### ISSUE THREAD

**Issue by MarkWojciechowicz** [theory/sqitch#320]
I am running through the tutorial for Postgres on a windows system: https://metacpan.org/pod/sqitchtutorial

When I run this command: _sqitch add appschema -n 'Add schema for all flipr objects.'_
I get this error: _Unknown arguments: schema, for, all, flipr, objects.'_

When I switch to double quotes: _sqitch add appschema -n "Add schema for all flipr objects."_
I get this error: _Multiple values at C:/Strawberry/perl/site/lib/Config/GitLike.pm line 631._

I'm guessing this is an issue specific with a windows environment.  Is there something I'm missing or another module I need to install?

mark

**Comment by theory** [comment]
I was able to replicate this issue by omitting the `--engine pg` option from the call to `sqitch init`. But with `--engine pg`, it worked fine -- although I did have to replace the single quotes with double quotes. Here's what I did (sorry for the screenshot, using a VM):

<img width="654" alt="screen shot 2017-04-20 at 9 08 50 pm" src="https://cloud.githubusercontent.com/assets/46604/25262545/a60fffa6-260d-11e7-99bd-de759d0da167.png">

Can you give that a shot?

**Comment by bbhandari12345** [comment]
you have still error

**Comment by bbhandari12345** [comment]
Adding registry tables to db:pg://postgres:@localhost:5432/b
Multiple values at C:/Strawberry/perl/site/lib/Config/GitLike.pm line 650.

**Comment by theory** [comment]
What does your `sqitch.conf` look like?

**Comment by theory** [comment]
What, exactly, is the command you're using, @YulkaSem, and what's the output? Thanks.
