### ISSUE TITLE
Sqitch connecting to local instead of remote host

### ISSUE THREAD

**Issue by abrim** [theory/sqitch#326]
When trying sqitch deploy on a remote host (Google Cloud SQL Postgresql instance) I'm getting the following error:
```
$ sqitch deploy
Adding registry tables to dev
psql: FATAL:  database "dev" does not exist
"psql" unexpectedly returned exit value 2
```

& no sqitch schema is created on the database.

If I create a local database of the same name, I get:
```
$ sqitch deploy
Adding registry tables to dev
ERROR:  relation "changes" does not exist
```

& sqitch schema is created on the local database instead of the remote.

connection uri is:
`db:pg:///dev?hostaddr=[IP Address]&host=[Project]:[Instance]&user=admin&sslmode=verify-full&sslrootcert=../certs/server-ca.pem&sslcert=../certs/client-cert.pem&sslkey=../certs/client-key.pem`

Server logs from the deploy only show a failed select query on table changes (which does not exist), so it is clear connection is happening properly at some point, just not when creating the initial schema.
```
$ sqitch --version
sqitch (App::Sqitch) 0.9995
```

**Comment by theory** [comment]
Try `db:pg://[IP Address]/dev`.

**Comment by abrim** [comment]
Solved (sort of):
Putting `db:pg://[User]@[Host]` (with a url encoded ':') and adding the host/ip to `/etc/hosts` seems to be the only thing that works.

Tried using `.pg_service.conf` & a variety of other solutions, but they all fail either because host /= ipaddr or because of the stupid `:` in the host name.

Thanks for the prompt reply.

**Comment by theory** [comment]
you…you have a colon in the host name? Yeash.
