### ISSUE TITLE
Cannot revert function changes which depends on a return type change

### ISSUE THREAD

**Issue by HuanfengMa** [theory/sqitch#327]
I tried to search all reported issues but didn't seem find any related ones. However, the issue I am having is actually common. 
Suppose you have  a function B defined which return SETOF type A, revert for the initial adding is OK since you simply just get rid of A and B. But issue happens when you want to make a change to type A by adding new attributes and change B to return these new attributes. Deployment works. But when you want to revert the changes made to function B, it always complain: "ERROR:  return type mismatch in function declared to return A..., DETAIL:  Final statement returns too few columns."
It looks like the revert first change B to previous version which return previous A type with less attributes. I already declare B requires A during my changes but it still complains during revert. Is this a bug? If not, can anybody tells me how to get the changes reverted correctly?

**Comment by theory** [comment]
Hi. I think that the [mail list](https://groups.google.com/forum/#!forum/sqitch-users) is a better place to take questions like this. I suggest you post some examples there. The upshot, though, is that I assume you're using PostgreSQL, and you'll have to update these two objects (the custom data type and the function) in sync. Like have the revert script first drop the function, then change the type, then create the function again.
