### ISSUE TITLE
[postgres] DDL statements should be rollbacked thanks to native transaction rollback system

### ISSUE THREAD

**Issue by docteurklein** [theory/sqitch#330]
Currently, `sqitch deploy --verify` can end up in an inconsistent/blocked state, if the `verify` script contains a typo (for example) and that you didn't yet write a `revert` script (or an incorrect `revert`).

```
LOG:  statement: begin
LOG:  statement: LOCK TABLE changes IN EXCLUSIVE MODE
LOG:  statement: BEGIN;
LOG:  statement: CREATE TABLE sale_point_positioning (
	  id UUID NOT NULL,
	  campaign_id UUID NOT NULL,
	  sale_point_id UUID NOT NULL,
	  sale_point_group_id UUID NOT NULL,
	  created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
	  PRIMARY KEY(id)
	);
LOG:  statement: COMMIT;
LOG:  statement: BEGIN;
LOG:  statement: SELECT id, created_at, campaign_id, sale_point_id, group_id FROM sale_point_positioning WHERE false;
ERROR:  column "group_id" does not exist at character 52
STATEMENT:  SELECT id, created_at, campaign_id, sale_point_id, group_id FROM sale_point_positioning WHERE false;
LOG:  statement: rollback
LOG:  statement: begin
LOG:  statement: LOCK TABLE changes IN EXCLUSIVE MODE
LOG:  statement: BEGIN;
LOG:  statement: COMMIT;
```

As you can see, there is a typo in the `verify` script, and the revert script is empty.

This means that my migration is considered "failed", even tho the table is created.
I'm thus in a state where I have to manually make the revert.

Would it be possible to make the `COMMIT;` **only** if the `verify` script executed successfully?

**Comment by theory** [comment]
Nope, the scripts are run completely independently. The expectation with Sqitch is that you're doing development, and if you make an error like this, you manually correct it before you commit the typo-free verify and revert scripts to your repository. The goal is to have clean change scripts when you tag and release, so test your scripts carefully before you release.
