### ISSUE TITLE
sqitch deploy returns: 'nvalid bool 'true - on CRLF

### ISSUE THREAD

**Issue by aranwe** [theory/sqitch#338]
Hello everyone,

Sqitch prints weird error message:
`'nvalid bool 'true`
(Including the singlequotes and missing "I")

when running deploy (possibly other commands) if the sqitch.conf + rest of the sqitch project files have CRLF  line endings on Linux.

Took me a while to figure out the cause of this (I have sqitch&pgsql in Virtualbox Linux machine and using shared folder from Windows).

**Comment by theory** [comment]
Redirected the bug report in bestpractical/config-gitlike#13. Thanks!

**Comment by theory** [comment]
bestpractical/config-gitlike#13 was fixed and [Config::GitLike 1.17](http://search.cpan.org/~alexmv/Config-GitLike-1.17/) released. Upgrade that module and you should be good (cc #310).
