### ISSUE TITLE
Question: Ability to Dump DB

### ISSUE THREAD

**Issue by BenMorganIO** [theory/sqitch#345]
Hey there,

I'm currently working on a project to integrate with Sqitch. I'm in need of doing a simple curl from our repo to grab, say, a `structure.sql` and then load that up as the structure in the DB for a CI. This way the CI doesn't need to be aware of Sqitch, it just needs the SQL to load up.

Does sqitch ever do a DB dump or the like? This would make application setup quite easy on CIs.

**Comment by theory** [comment]
I suggest you post your question to the [mail list](https://groups.google.com/forum/#!forum/sqitch-users).
