### ISSUE TITLE
Document or Allow Postgres PSQL Parameterization From Sqitch

### ISSUE THREAD

**Issue by eric-aldinger** [theory/sqitch#347]
PSQL allows for variables to be passed on the command line that allow for SQL script interpolation. This allows a great deal of flexibility in deployment. More importantly it takes user/password strings out of code and allows the configuration management tooling to own secrets management.  

Is there a way to pass variables into sqitch that allows them to be available to the underlying database connection manager? 

An example of a non-sqitch deploy would be 
```
psql --file=${i} -h ${dbhost} -p ${dbport} -d "postgres" -U ${dbuser} -v admin_role=${dbuser} -v user_password=${dbpassword}
```

With the example code being 
```
BEGIN;
  CREATE USER some_user WITH PASSWORD :'user_password' VALID UNTIL 'infinity';
COMMIT;

```

**Comment by theory** [comment]
Yep, see the`--set` option and `deploy.variables` in [`sqitch help deploy`](/theory/sqitch/blob/master/lib/sqitch-deploy.pod).

Also, consider joining the [mail list](https://groups.google.com/forum/#!forum/sqitch-users) for posting questions.

**Comment by eric-aldinger** [comment]
You are amazing. Thanks. 

And will use the mail list going forward.
