### ISSUE TITLE
Error when using on OS X

### ISSUE THREAD

**Issue by gilbert** [theory/sqitch#352]
Hi, I'm trying to follow [this sqitch tutorial](https://metacpan.org/pod/sqitchtutorial), but I'm getting an error. Here are the commands I ran:

```bash
$ brew tap theory/sqitch
$ brew install sqitch
$ sqitch init flipr --uri https://github.com/theory/sqitch-intro/ --engine pg
$ sqitch add appschema -n 'Add schema for all flipr objects.
$ createdb flipr_test
$ sqitch deploy db:pg:flipr_test
DBD::Pg 2.0 required to manage PostgreSQL
```

Am I missing a dependency of some sort? I thought brew might take care of that.

**Comment by theory** [comment]
You need to install the DBD::Pg module. Try `brew install sqitch_pg`.

Also,for questions, I recommend posting to the [mail list](https://groups.google.com/forum/#!forum/sqitch-users), rather than opening an issue.
