### ISSUE TITLE
Can't set the mysql username from .my.cnf when first connecting to database

### ISSUE THREAD

**Issue by ealter** [theory/sqitch#353]
I've been playing around with not specifying the username in the `sqitch.conf`. Here's scrubbed version of my target:

```
[target "production"]                                                          
        uri = db:mysql://mysql.example.com/test_db                     
        registry = test_db
```

In my ~/.my.cnf, I specify the `user` and `password` for this server.
```
[client]
password=######
user=eliot
```

Now this works all fine-and-dandy when my login username is also 'eliot'. I've verified it's using this file since I get the following error if I change it to 'eliot2' in ~/.my.cnf:

```
$ sqitch verify --target production                                              
Verifying production                                                           
  * initial_dump ......... ERROR 1045 (28000): Access denied for user 'eliot2'@'mysql.example.com' (using password: YES)                             
# Verify script "verify/initial_dump.sql" failed.
```

But when I run this same command inside of a docker image (where the user is 'root'), it fails to connect the first time:
```
$ sqitch verify --target production
Access denied for user 'root'@'mysql.example.com' (using password: YES)
```

Note here how the username here is 'root' and not 'eliot2' or 'eliot'.

When I hardcoded 'eliot' into [lib/App/Sqitch/Engine/mysql.pm](https://github.com/theory/sqitch/blob/470f4d67caa0ba3b1b90a5f697307647e0caa2aa/lib/App/Sqitch/Engine/mysql.pm#L59), it then passes the first verification step and fails with the 2nd `eliot2` error from above. If I then fix the username in `~/.my.cnf` as well as continue hardcoding my username here, then it succeeds.

Dockerfile I'm using to reproduce this change:

```
FROM perl:latest                                                               
WORKDIR /src                                                                   

RUN apt-get update \                                                           
    && apt-get install -y --no-install-recommends mysql-client dumb-init \     
    && apt-get clean \                                                         
    # Now install the application                                              
    && cpan DBD::mysql \                                                       
    && cpan App::Sqitch \                                                      
    # We need MySQL::Config so that we can read the ~/.my.cnf file. See        
    # https://github.com/theory/sqitch/issues/261                              
    && cpan MySQL::Config                                                      

ENTRYPOINT ["dumb-init", "/usr/local/bin/sqitch"]
```

I don't want to put the username into my sqitch.conf since different developers on my team have different login credentials to production mysql.

**Comment by theory** [comment]
I don't understand. Doesn't it work when the system user is root if you set the username in `~/.my.cnf` to "root"?

**Comment by ealter** [comment]
So the issue here is that sqitch first tries to connect/login with the system user. If that succeeds, then it executes the mysql statements using the user in .my.cnf

**Comment by ealter** [comment]
So root/root does work, but in my case, I don't want to use my own login to mysql, not the root user. I'm only 'root' in this case because sqitch is running inside of a docker container.

**Comment by theory** [comment]
You can specify the username in the Sqitch config:

    [target "production"]                                                          
            uri = db:mysql://eliot@mysql.example.com/test_db                     
            registry = test_db

That should make it use the user consistently.

**Comment by ealter** [comment]
Yes that does work, but I don't want to put the user in sqitch.conf since I'm checking that into git. Each developer on my team has their own user/password combination to the database. Therefore, if I set it in sqitch.conf and pushed, they would have to change it there before using the app.

**Comment by theory** [comment]
Or provide a separate target config for each of them.

I guess we could teach mysql.pm to read the username from the config file, too. Something like this (untested, give it a try):

    diff --git a/lib/App/Sqitch/Engine/mysql.pm b/lib/App/Sqitch/Engine/mysql.pm
    index ebfb2d79..a4cc80b9 100644
    --- a/lib/App/Sqitch/Engine/mysql.pm
    +++ b/lib/App/Sqitch/Engine/mysql.pm
    @@ -10,7 +10,7 @@ use Locale::TextDomain qw(App-Sqitch);
     use App::Sqitch::Plan::Change;
     use Path::Class;
     use Moo;
    -use App::Sqitch::Types qw(DBH URIDB ArrayRef Bool Str);
    +use App::Sqitch::Types qw(DBH URIDB ArrayRef Bool Str HashRef);
     use namespace::autoclean;
     use List::MoreUtils qw(firstidx);
 
    @@ -39,6 +39,25 @@ sub registry_destination {
         return $uri->as_string;
     }
 
    +has _mycnf => (
    +    is => 'rw',
    +    isa => HashRef,
    +    default => sub {
    +        eval 'require MySQL::Config; 1' or return {};
    +        return \MySQL::Config::parse_defaults('my', [qw(client mysql)]);
    +    },
    +);
    +
    +sub username {
    +    my $self = shift;
    +    return $self->SUPER::username || $self->_mycnf->{user};
    +}
    +
    +sub password {
    +    my $self = shift;
    +    return $self->SUPER::password || $self->_mycnf->{password};
    +}
    +
     has dbh => (
         is      => 'rw',
         isa     => DBH,
    @@ -46,17 +65,8 @@ has dbh => (
         default => sub {
             my $self = shift;
             $self->use_driver;
    -
             my $uri = $self->registry_uri;
    -        my $pass = $self->password || do {
    -            # Read the default MySQL configuration.
    -            # http://dev.mysql.com/doc/refman/5.0/en/option-file-options.html
    -            if (eval 'require MySQL::Config; 1') {
    -                my %cfg = MySQL::Config::parse_defaults('my', [qw(client mysql)]);
    -                $cfg{password};
    -            }
    -        };
    -        my $dbh = DBI->connect($uri->dbi_dsn, scalar $self->username, $pass, {
    +        my $dbh = DBI->connect($uri->dbi_dsn, scalar $self->username, $self->password, {
                 PrintError           => 0,
                 RaiseError           => 0,
                 AutoCommit           => 1,

**Comment by ealter** [comment]
I tried your diff and got the following error:

```
root@c3ce2425b426:/src# sqitch verify --target production                      
Reference \"password" did not pass type constraint "HashRef" (in $args->{"_mycnf"}) at /usr/local/lib/perl5/site_perl/5.26.0/App/Sqitch/Engine.pm line 117                                                                                                                                                       
    Reference \"password" did not pass type constraint "HashRef" (in $args->{"_mycnf"})                                                            
    "HashRef" is defined as: (Ref::Util::XS::is_plain_hashref($_))
```

**Comment by theory** [comment]
Hrm. Try changing line 47 of mysql.pm from:

        return \MySQL::Config::parse_defaults('my', [qw(client mysql)]);

To:

        return scalar MySQL::Config::parse_defaults('my', [qw(client mysql)]);

**Comment by ealter** [comment]
Sweet! That fix worked perfectly.

Do you know when you're going to cut your next release?

**Comment by ealter** [comment]
For now, I just added the following to my Dockerfile

```
# Apply the patch in https://github.com/theory/sqitch/issues/353#issuecomment-327803364
COPY github_issue_353 /tmp/

RUN chmod 644 /usr/local/lib/perl5/site_perl/5.26.0/App/Sqitch/Engine/mysql.pm \
    && patch /usr/local/lib/perl5/site_perl/5.26.0/App/Sqitch/Engine/mysql.pm < /tmp/github_issue_353 \
    && chmod 444 /usr/local/lib/perl5/site_perl/5.26.0/App/Sqitch/Engine/mysql.pm
```

**Comment by theory** [comment]
Not sure, sometime this month, I think. Thanks for the report, @ealter!
