### ISSUE TITLE
Sqitch does not namespace its internal mysql tables

### ISSUE THREAD

**Issue by ealter** [theory/sqitch#354]
Sqitch creates the following [database tables](https://github.com/theory/sqitch/blob/3a0dec67ea5d9a6b6917f53122a2a414ecc085de/lib/App/Sqitch/Engine/mysql.sql) to track its internal state:

- releases
- projects
- changes
- tags
- dependencies
- events

We have an existing database that we'd like to migrate to sqitch. Unfortunately, it has an existing table named `tags` which conflicts with sqitch's internal table.

Is there a way to namespace the tables that sqitch creates (like `sqitch_tags`)? Is there a way to make this change in a backwards compatible way so that it doesn't break existing sqitch deployments?

**Comment by theory** [comment]
What RDBMS? Sqitch mostly tries to keep its tables in its own schema (Postgres) or database (MySQL).

**Comment by ealter** [comment]
I'm using mysql. Here's a subset of our sqitch.conf:

```
[core]
        engine = mysql
[target "vagrant"]
        uri = db:mysql://developer:password@localhost/analytics
        registry = analytics
```

sqitch creates all of its database tables inside `analytics` database in this case.

**Comment by theory** [comment]
Yeah, just use a different registry and it will put them in a different database.

**Comment by ealter** [comment]
Hmm, I keep getting 'permission denied' errors.

```
$ sqitch verify
Access denied for user 'developer'@'%' to database 'sqitch'
```

I already tried the following:
```
GRANT ALL PRIVILEGES ON sqitch.* TO 'developer'@'%';
FLUSH PRIVILEGES
```

It's interesting here that it's not saying `USING PASSWORD (YES)`. I wonder if it's ignoring auth somewhere?

**Comment by theory** [comment]
Does the switch database exist? Can you connect to it with the `mysql` client and the `developer` username?

**Comment by ealter** [comment]
Yep I can connect to it using that username:

`docker exec -it mysql mysql sqitch -u developer -p`

**Comment by ealter** [comment]
Would it make things easier if we did a google hangout and debugged this together?

**Comment by ealter** [comment]
I have no idea what happened, but it suddenly works. I'll close this issue for now unless it pops up again.

**Comment by theory** [comment]
That should do you, but it's a valid issue to want a prefix, which is what #247 is all about.
