### ISSUE TITLE
Feature Request: squash support for SQL statements

### ISSUE THREAD

**Issue by psankar** [theory/sqitch#355]
It would be nice if sqitch can support squashing SQL statements. I will explain what I mean by that.

I have a first file, where I do: `CREATE TABLE X (A TEXT)`
In the second file, I do: `DROP TABLE X; CREATE TABLE Y (A TEXT)`
In the third file, I do: `CREATE TABLE Z (B TEXT)`

Now after squashing, I just need to have a single .sql file with just the lines: `CREATE  TABLE Y (A TEXT); CREATE TABLE Z (B TEXT);` The temporary table X that was created in first file is no longer needed.

This is more like a pg_dump taken after a `sqitch deploy`.

Such a squashing option will be very useful in setting up Continuous Integration Testing environment, without having to create the database, setup every obsolete schema change.

Also, this has an added benefit of making our CI builds faster (no need for multiple DDLs) and lighter (no need to install sqitch and its dependencies). Every second saved in CI gives tremendous cost and time benefits, for the companies as well as for developer productivity.

Thanks for sqitch, I love using sqitch and cannot believe how I was able to survive without this so far.

**Comment by theory** [comment]
I can see why you would find this useful, but Sqitch intentionally understands nothing about SQL or any other database dialect, except for the management of the registry schema. You might be able to get some suggestions for how to get something like this feature by posting to the [mail list](https://groups.google.com/forum/#!forum/sqitch-users).
