### ISSUE TITLE
Disable sqitch reverts for specific targets (production)

### ISSUE THREAD

**Issue by pschwyter** [theory/sqitch#360]
Revert scripts are very useful when there are multiple people contributing migrations to the db since it's likely the plan can begin to diverge between members' respective environments. Revert scripts allow us to rebase and get back on track.

However, revert scripts are scary in production as it would result in losing your production data. Is there any way to still create revert scripts and have them disabled for specific targets?

**Comment by theory** [comment]
If you bundle your changes into a release for production (e.g., build an RPM with the changes and deploy the RPM to the server to make the deploy), you can just delete the `deploy` directory before you build the distribution.

That's about it, though.
