### ISSUE TITLE
revert and rebase should exit with 0 except in case of error

### ISSUE THREAD

**Issue by EmilGerth** [theory/sqitch#363]
Similar to the issue #147, the revert command returns 1 if there is nothing to revert, and 2 if there is an actual error with the reversion. Per the discussion at that issue, this is unexpected and maybe undesirable, as most applications expect 0 unless the operation actually failed.

The known workaround is to test the return code and only throw an error if the value is >= 2.

**Comment by theory** [comment]
Cargo-cult from 70d0077.
