### ISSUE TITLE
How to install sqitch on Ubuntu 14.04.5 LTS

### ISSUE THREAD

**Issue by lifeiscontent** [theory/sqitch#364]
when I run `sudo apt-get install sqitch` it says the package can't be found.

**Comment by theory** [comment]
We don't maintain OS packages, but it looks like you might be able to get Sqitch on Ubuntu [here](https://launchpad.net/ubuntu/+source/sqitch), though it's kind of old…

**Comment by lifeiscontent** [comment]
@theory how do I build from source? Which packages do I need?

**Comment by theory** [comment]
Lots of ways. See the [home page](http://sqitch.org/) for CPAN, Docker, Debian, and a ton of other installation options.
