### ISSUE TITLE
Store migrations themselves in the sqitch tables

### ISSUE THREAD

**Issue by jwoudenberg** [theory/sqitch#366]
First of all, thanks for your work on this awesome piece of software!

I have a question slash feature request, but it's all together possible it just stems from a lack of understanding on my part about how I should be using Sqitch or of safety considerations.

Suppose I'm working on a git branch `bears` that contains a sqitch.plan file with the following migrations: `a -> b -> c`. I'm switching to a branch `ants` that has migrations `a -> d -> e` and would like to migrate my database to the schema to reflect the plan on this branch. To achieve this, in my understanding, I need to revert until migration `a` on branch `bears`, then switch to branch `ants` and deploy.

In my ideal world I could simply switch to branch `ants` and run a single command like `sqitch deploy`. Sqitch would figure out `a` is the common ancestor of the current migration state and the local plan, roll back the current state to this common ancestor, then roll forward to the state specified by the current branch. Because this is a dangerous operation that can potentially drop a lot of data, the user would probably need to see an overview of changes that would be applied and get the opportunity to accept / reject this plan.

Technically, the one problem I see with this is that on branch `ants`, the deploy and revert scripts for migrations `b` and `c` are not around. When I would manually try to revert migrations `b` and `c` on the `ants` branch, Sqitch gives me an error. This brings me back to the question in the title of this issue. In its 'changes' table Sqitch currently references migration scripts outside of that database. What if it would actually store the deploy, verify, and revert scripts of any migration it deploys? It would remove the dependency Sqitch has on the state of the code and ensure reverts of migrations can always be run, regardless of the current state of the code.

**Comment by theory** [comment]
You want [`sqitch help checkout`][(https://metacpan.org/pod/sqitch-checkout).

I also recommend that you join the [mail list](https://groups.google.com/forum/#!forum/sqitch-users). Great place for questions like this.

**Comment by jwoudenberg** [comment]
Thank you!
