### ISSUE TITLE
Deployment of identical scripts fails

### ISSUE THREAD

**Issue by eric-brechemier** [theory/sqitch#367]
In the context of a migration of changes from one plan to another, I attempted to deploy a list of changes with identical, empty deployment scripts.

This fails in sqitch version 0.9993:

```
Server: deploy new changes for [NEW] plan (forward-only)
Deploying changes to db:pg:[DB]
  + [CHANGE1] .. ok
  + [CHANGE2] .. ERROR:  duplicate key value violates unique constraint "changes_project_script_hash_key"
DETAIL:  Key (project, script_hash)=([NEW], da39a3ee5e6b4b0d3255bfef95601890afd80709) already exists.
not ok
Reverting to [CHANGE0]  - [CHANGE1] .. 
ok
Deploy failed
```

**Comment by theory** [comment]
It's intentional. See #200 for details. Can you add a newline or something to one of the scripts?

**Comment by eric-brechemier** [comment]
@theory I don't see how the  `script_hash` is related to the discussion in #200.

> Can you add a newline or something to one of the scripts?

Yes, I added a comment with the file name in each script instead of leaving the files empty.

I wanted to avoid the use of `--log-only` option, which would have been an alternative, but was less convenient in the context of our automatic deployment scripts.

**Comment by theory** [comment]
It lays the groundwork for a future `merge` command to be able to fall back on deploy script signatures to determine deployments for when plans diverge, so it can figure out how to merge deployments and end up with a proper deployment timeline.

**Comment by eric-brechemier** [comment]
OK.
