### ISSUE TITLE
Error when trying to use sqitch-add with --change key

### ISSUE THREAD

**Issue by Innokentiy-Alaytsev** [theory/sqitch#383]
Hello!

I have encountered an error while trying to use sqitch-add with --change-name key. A simple call like any of the following

```
sqitch add -c test_change
sqitch add --change test_change
```

results in the following error:

> Use of uninitialized value $name in exists at /usr/share/perl5/App/Sqitch/Plan.pm line 897.
> Use of uninitialized value $name in pattern match (m//) at /usr/share/perl5/App/Sqitch/Plan.pm line 898.
> Use of uninitialized value $name in pattern match (m//) at /usr/share/perl5/App/Sqitch/Plan.pm line 903.
> "{name}" is invalid: changes must not begin with punctuation, contain "@", ":", "#", or blanks, or end in punctuation or digits following punctuation

I am using sqitch 0.9993 (`sqitch (App::Sqitch) 0.9993`) from the official repository on Ubuntu 16.04 under WSL. I have tried to install sqitch from CPAN, but it has failed with some errors that I do not understand.

A quick look at the sources for versions 0.9993 and 0.9998 around the location, given in the error message, gave me no clue - the source code is exactly the same. However, I do not know Perl and did not try to check the whole trace until the failure.

**Comment by theory** [comment]
I am unable to replicate either with `master` or via the v0.9993 branch. Is this a problem with a freshly initialized repo?

```
> mkdir tmp
> cd tmp 
> ../t/sqitch init --engine pg foo               
Created sqitch.conf
Created sqitch.plan
Created deploy/
Created revert/
Created verify/
> sqitch add -c a_change
Created deploy/a_change.sql
Created revert/a_change.sql
Created verify/a_change.sql
Added "a_change" to sqitch.plan
```

**Comment by theory** [comment]
Oh, what version are you running? This issue was fixed in v0.9995, in commit ebf6a95c7.

**Comment by Innokentiy-Alaytsev** [comment]
I am using sqitch 0.9993 (sqitch (App::Sqitch) 0.9993) from the official repository on Ubuntu 16.04.

**Comment by theory** [comment]
Ah, yeah, you'll need to upgrade.
