### ISSUE TITLE
Tutorial Improvements: recommend how to get started with existing databases that aren't using sqitch

### ISSUE THREAD

**Issue by joevandyk** [theory/sqitch#77]
I'm guessing this is will be the case for most people coming to sqitch. 

The existing schema should be known to sqitch, so that sqitch can bootstrap new development databases with the same structure. But when sqitch deploys to existing production databases, sqitch shouldn't try to deploy the already existing schema.

**Comment by theory** [comment]
This is a fairly common question, and has been discussed on the [mail list](https://groups.google.com/forum/#!forum/sqitch-users) reasonably often. here' [one thread](https://groups.google.com/d/msg/sqitch-users/5ua5VCGDzZM/ZBnuCujnCgAJ) on the topic. HTH!

**Comment by unamachivaym** [comment]
Yup thank you @theory. got that worked. How sqitch is different than flyway because i could see flyway gives almost the same flexibility even allows to develop advance scripts using java itself. can you give some pointers which explains that. basically flyway vs sqitch.

**Comment by theory** [comment]
Sorry, never heard of Flyway. I suggest you post your question to the mail list; someone else may well have some context to share.
